python manage.py logcommand "fetch ftc"
python manage.py logcommand "fetch grants"
python manage.py logcommand "fetch grant-recipients"
python manage.py logcommand "update financial-year"
python manage.py logcommand "update grants"
python manage.py logcommand "update grant-recipient-type"