# Generated by Django 5.0.4 on 2024-04-18 22:29

import django.db.models.deletion
import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FunderTag",
            fields=[
                (
                    "tag",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Funder",
            fields=[
                (
                    "org_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("charity_number", models.CharField(max_length=10)),
                ("name_registered", models.CharField(max_length=255)),
                (
                    "name_manual",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "segment",
                    models.CharField(
                        choices=[
                            ("Community Foundations", "Community Foundations"),
                            ("Corporate Foundations", "Corporate Foundations"),
                            ("Family Foundations", "Family Foundations"),
                            ("Fundraising Grantmakers", "Fundraising Grantmakers"),
                            (
                                "Government/lottery endowed grantmakers",
                                "Government/lottery endowed grantmakers",
                            ),
                            ("Member/Trade funded", "Member/Trade funded"),
                            ("Donor Advised Funds", "Donor Advised Funds"),
                            ("Grants to individuals", "Grants to individuals"),
                            ("Wellcome Trust", "Wellcome Trust"),
                            ("General grantmakers", "General grantmakers"),
                            ("Small grant makers", "Small grant makers"),
                            (
                                "Charity Grantmakers: NHS/Hospital Foundations",
                                "Charity Grantmakers: NHS/Hospital Foundations",
                            ),
                            ("Charity Grantmakers", "Charity Grantmakers"),
                            ("Government: central", "Government: central"),
                            ("Government: local", "Government: local"),
                            ("Government: Devolved", "Government: Devolved"),
                            (
                                "Government: Arms Length Body",
                                "Government: Arms Length Body",
                            ),
                            ("Lottery Distributors", "Lottery Distributors"),
                            ("Companies", "Companies"),
                        ],
                        default="General grantmakers",
                        max_length=50,
                    ),
                ),
                ("included", models.BooleanField(default=True)),
                ("makes_grants_to_individuals", models.BooleanField(default=False)),
                ("date_of_registration", models.DateField(blank=True, null=True)),
                ("activities", models.TextField(blank=True, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "name",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.comparison.Coalesce(
                            "name_manual", "name_registered"
                        ),
                        output_field=models.CharField(max_length=255),
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(blank=True, to="ukgrantmaking.fundertag"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FunderYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("financial_year_end", models.DateField()),
                ("financial_year_start", models.DateField(blank=True, null=True)),
                (
                    "income_registered",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "income_manual",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "income",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.comparison.Coalesce(
                            "income_manual", "income_registered"
                        ),
                        output_field=models.BigIntegerField(),
                    ),
                ),
                (
                    "spending_registered",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "spending_manual",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "spending",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.comparison.Coalesce(
                            "spending_manual", "spending_registered"
                        ),
                        output_field=models.BigIntegerField(),
                    ),
                ),
                (
                    "spending_charitable_registered",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "spending_charitable_manual",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "spending_charitable",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.comparison.Coalesce(
                            "spending_charitable_manual",
                            "spending_charitable_registered",
                        ),
                        output_field=models.BigIntegerField(),
                    ),
                ),
                (
                    "spending_grant_making_registered",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "spending_grant_making_manual",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "spending_grant_making",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.comparison.Coalesce(
                            "spending_grant_making_manual",
                            "spending_grant_making_registered",
                        ),
                        output_field=models.BigIntegerField(),
                    ),
                ),
                (
                    "spending_grant_making_individuals_registered",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "spending_grant_making_individuals_manual",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "spending_grant_making_individuals",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.comparison.Coalesce(
                            "spending_grant_making_individuals_manual",
                            "spending_grant_making_individuals_registered",
                        ),
                        output_field=models.BigIntegerField(),
                    ),
                ),
                (
                    "spending_grant_making_institutions_registered",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "spending_grant_making_institutions_manual",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "spending_grant_making_institutions",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.comparison.Coalesce(
                            "spending_grant_making_institutions_manual",
                            "spending_grant_making_institutions_registered",
                        ),
                        output_field=models.BigIntegerField(),
                    ),
                ),
                (
                    "total_net_assets_registered",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "total_net_assets_manual",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "total_net_assets",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.comparison.Coalesce(
                            "total_net_assets_manual", "total_net_assets_registered"
                        ),
                        output_field=models.BigIntegerField(),
                    ),
                ),
                (
                    "funds_registered",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "funds_manual",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "funds",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.comparison.Coalesce(
                            "funds_manual", "funds_registered"
                        ),
                        output_field=models.BigIntegerField(),
                    ),
                ),
                (
                    "funds_endowment_registered",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "funds_endowment_manual",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "funds_endowment",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.comparison.Coalesce(
                            "funds_endowment_manual", "funds_endowment_registered"
                        ),
                        output_field=models.BigIntegerField(),
                    ),
                ),
                (
                    "funds_restricted_registered",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "funds_restricted_manual",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "funds_restricted",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.comparison.Coalesce(
                            "funds_restricted_manual", "funds_restricted_registered"
                        ),
                        output_field=models.BigIntegerField(),
                    ),
                ),
                (
                    "funds_unrestricted_registered",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "funds_unrestricted_manual",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "funds_unrestricted",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.comparison.Coalesce(
                            "funds_unrestricted_manual", "funds_unrestricted_registered"
                        ),
                        output_field=models.BigIntegerField(),
                    ),
                ),
                ("employees_registered", models.IntegerField(blank=True, null=True)),
                ("employees_manual", models.IntegerField(blank=True, null=True)),
                (
                    "employees",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.comparison.Coalesce(
                            "employees_manual", "employees_registered"
                        ),
                        output_field=models.BigIntegerField(),
                    ),
                ),
                ("checked_on", models.DateTimeField(auto_now=True)),
                ("checked_by", models.CharField(blank=True, max_length=255, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "funder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ukgrantmaking.funder",
                    ),
                ),
            ],
        ),
    ]
