# Generated by Django 5.0.4 on 2024-04-18 23:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ukgrantmaking", "0002_alter_funder_segment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funder",
            name="segment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Donor Advised Fund", "Donor Advised Fund"),
                    ("Wellcome Trust", "Wellcome Trust"),
                    ("Charity", "Charity"),
                    ("Lottery Distributor", "Lottery Distributor"),
                    ("Arms Length Body", "Arms Length Body"),
                    ("Corporate Foundation", "Corporate Foundation"),
                    ("Family Foundation", "Family Foundation"),
                    ("Fundraising Grantmaker", "Fundraising Grantmaker"),
                    ("General grantmaker", "General grantmaker"),
                    ("Member/Trade Funded", "Member/Trade Funded"),
                    ("NHS/Hospital Foundation", "NHS/Hospital Foundation"),
                    ("Government/Lottery Endowed", "Government/Lottery Endowed"),
                    ("Small grantmaker", "Small grantmaker"),
                    ("Community Foundation", "Community Foundation"),
                    ("Local", "Local"),
                    ("Central", "Central"),
                    ("Devolved", "Devolved"),
                ],
                default="General grantmaker",
                max_length=50,
                null=True,
            ),
        ),
    ]
