# Generated by Django 5.0.4 on 2024-04-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ukgrantmaking", "0006_alter_funderyear_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="funderyear",
            options={"ordering": ["funder", "-financial_year_end"]},
        ),
        migrations.AlterField(
            model_name="funder",
            name="charity_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="funder",
            name="org_id",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
