# Generated by Django 5.0.4 on 2024-04-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ukgrantmaking",
            "0007_alter_funderyear_options_alter_funder_charity_number_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="funder",
            name="latest_grantmaking",
            field=models.DecimalField(
                blank=True, db_index=True, decimal_places=2, max_digits=16, null=True
            ),
        ),
        migrations.AddField(
            model_name="funderyear",
            name="financial_year",
            field=models.CharField(
                blank=True,
                choices=[
                    ("2029-30", "2029-30"),
                    ("2028-29", "2028-29"),
                    ("2027-28", "2027-28"),
                    ("2026-27", "2026-27"),
                    ("2025-26", "2025-26"),
                    ("2024-25", "2024-25"),
                    ("2023-24", "2023-24"),
                    ("2022-23", "2022-23"),
                    ("2021-22", "2021-22"),
                    ("2020-21", "2020-21"),
                    ("2019-20", "2019-20"),
                    ("2018-19", "2018-19"),
                    ("2017-18", "2017-18"),
                    ("2016-17", "2016-17"),
                    ("2015-16", "2015-16"),
                    ("2014-15", "2014-15"),
                    ("2013-14", "2013-14"),
                    ("2012-13", "2012-13"),
                    ("2011-12", "2011-12"),
                    ("2010-11", "2010-11"),
                    ("2009-10", "2009-10"),
                    ("2008-09", "2008-09"),
                    ("2007-08", "2007-08"),
                    ("2006-07", "2006-07"),
                    ("2005-06", "2005-06"),
                    ("2004-05", "2004-05"),
                    ("2003-04", "2003-04"),
                    ("2002-03", "2002-03"),
                    ("2001-02", "2001-02"),
                    ("2000-01", "2000-01"),
                ],
                db_index=True,
                max_length=9,
                null=True,
            ),
        ),
    ]
