# Generated by Django 5.0.4 on 2024-04-19 10:39

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ukgrantmaking", "0008_funder_latest_grantmaking_funderyear_financial_year"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="funder",
            options={"ordering": ["-latest_grantmaking"]},
        ),
        migrations.RemoveField(
            model_name="funderyear",
            name="spending_grant_making",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.expressions.CombinedExpression(
                    models.F("spending_grant_making_individuals"),
                    "+",
                    models.F("spending_grant_making_institutions"),
                ),
                output_field=models.BigIntegerField(),
            ),
        ),
        migrations.RemoveField(
            model_name="funderyear",
            name="spending_grant_making_manual",
        ),
        migrations.RemoveField(
            model_name="funderyear",
            name="spending_grant_making_registered",
        ),
        migrations.AddField(
            model_name="funderyear",
            name="spending_grant_making",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.expressions.CombinedExpression(
                    models.F("spending_grant_making_individuals"),
                    "+",
                    models.F("spending_grant_making_institutions"),
                ),
                output_field=models.BigIntegerField(),
            ),
        ),
    ]
