# Generated by Django 5.0.4 on 2024-04-19 10:43

import django.db.models.expressions
import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ukgrantmaking", "0009_alter_funder_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="funderyear",
            name="spending_grant_making",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.expressions.CombinedExpression(
                    django.db.models.functions.comparison.Coalesce(
                        models.F("spending_grant_making_individuals"), 0
                    ),
                    "+",
                    django.db.models.functions.comparison.Coalesce(
                        models.F("spending_grant_making_institutions"), 0
                    ),
                ),
                output_field=models.BigIntegerField(),
            ),
        ),
        migrations.AddField(
            model_name="funderyear",
            name="spending_grant_making",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.expressions.CombinedExpression(
                    django.db.models.functions.comparison.Coalesce(
                        models.F("spending_grant_making_individuals"), 0
                    ),
                    "+",
                    django.db.models.functions.comparison.Coalesce(
                        models.F("spending_grant_making_institutions"), 0
                    ),
                ),
                output_field=models.BigIntegerField(),
            ),
        ),
    ]
