# Generated by Django 5.0.4 on 2024-04-19 12:06

import django.db.models.expressions
import django.db.models.functions.comparison
import django.db.models.lookups
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ukgrantmaking", "0010_alter_funderyear_spending_grant_making"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="funderyear",
            name="spending_grant_making",
        ),
        migrations.AddField(
            model_name="funderyear",
            name="spending_grant_making",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Case(
                    models.When(
                        models.Q(
                            django.db.models.lookups.IsNull(
                                "spending_grant_making_individuals", False
                            ),
                            django.db.models.lookups.IsNull(
                                "spending_grant_making_institutions", False
                            ),
                            _connector="OR",
                        ),
                        then=django.db.models.expressions.CombinedExpression(
                            django.db.models.functions.comparison.Coalesce(
                                models.F("spending_grant_making_individuals"), 0
                            ),
                            "+",
                            django.db.models.functions.comparison.Coalesce(
                                models.F("spending_grant_making_institutions"), 0
                            ),
                        ),
                    )
                ),
                output_field=models.BigIntegerField(),
            ),
        ),
    ]
