# Generated by Django 5.0.4 on 2024-04-19 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ukgrantmaking", "0011_alter_funderyear_spending_grant_making"),
    ]

    operations = [
        migrations.CreateModel(
            name="FunderNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField()),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("added_by", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "funder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="ukgrantmaking.funder",
                    ),
                ),
            ],
        ),
    ]
