# Generated by Django 5.0.4 on 2024-04-19 13:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ukgrantmaking", "0014_alter_funderyear_spending_grant_making"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="funderyear",
            name="spending_grant_making_2",
        ),
    ]
