# Generated by Django 5.0.4 on 2024-04-19 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ukgrantmaking", "0015_remove_funderyear_spending_grant_making_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="funder",
            name="latest_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="funder_latest_year",
                to="ukgrantmaking.funderyear",
            ),
        ),
    ]
