# Generated by Django 5.0.4 on 2024-04-19 14:00

import django.db.models.expressions
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ukgrantmaking", "0016_funder_latest_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="funder",
            name="org_id_schema",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Case(
                    models.When(
                        models.Q(("org_id__startswith", "UKG-")),
                        then=models.Value("UKG"),
                    ),
                    default=django.db.models.functions.text.Left(
                        models.F("org_id"),
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.functions.text.StrIndex(
                                models.F("org_id"), models.Value("-")
                            ),
                            "-",
                            models.Value(1),
                        ),
                    ),
                ),
                output_field=models.CharField(max_length=255),
            ),
        ),
    ]
