# Generated by Django 5.0.4 on 2024-04-19 14:05

import django.db.models.expressions
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ukgrantmaking", "0018_alter_funder_org_id_schema"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="funder",
            name="org_id_schema",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Case(
                    models.When(
                        models.Q(("org_id__startswith", "UKG-")),
                        then=models.Value("UKG"),
                    ),
                    models.When(
                        models.Q(("org_id__startswith", "360G-")),
                        then=models.Value("UKG"),
                    ),
                    models.When(
                        models.Q(("org_id__startswith", "GB-CHC-")),
                        then=models.Value("GB-CHC"),
                    ),
                    models.When(
                        models.Q(("org_id__startswith", "GB-COH-")),
                        then=models.Value("GB-COH"),
                    ),
                    models.When(
                        models.Q(("org_id__startswith", "GB-SC-")),
                        then=models.Value("GB-SC"),
                    ),
                    models.When(
                        models.Q(("org_id__startswith", "GB-NIC-")),
                        then=models.Value("GB-NIC"),
                    ),
                    models.When(
                        models.Q(("org_id__startswith", "GB-LAE-")),
                        then=models.Value("GB-LAE"),
                    ),
                    models.When(
                        models.Q(("org_id__startswith", "GB-GOR-")),
                        then=models.Value("GB-GOR"),
                    ),
                    default=django.db.models.functions.text.Left(
                        models.F("org_id"),
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.functions.text.StrIndex(
                                models.F("org_id"), models.Value("-")
                            ),
                            "-",
                            models.Value(1),
                        ),
                    ),
                ),
                output_field=models.CharField(max_length=255),
            ),
        ),
        migrations.AddField(
            model_name="funder",
            name="org_id_schema",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Case(
                    models.When(
                        models.Q(("org_id__startswith", "UKG-")),
                        then=models.Value("UKG"),
                    ),
                    models.When(
                        models.Q(("org_id__startswith", "360G-")),
                        then=models.Value("UKG"),
                    ),
                    models.When(
                        models.Q(("org_id__startswith", "GB-CHC-")),
                        then=models.Value("GB-CHC"),
                    ),
                    models.When(
                        models.Q(("org_id__startswith", "GB-COH-")),
                        then=models.Value("GB-COH"),
                    ),
                    models.When(
                        models.Q(("org_id__startswith", "GB-SC-")),
                        then=models.Value("GB-SC"),
                    ),
                    models.When(
                        models.Q(("org_id__startswith", "GB-NIC-")),
                        then=models.Value("GB-NIC"),
                    ),
                    models.When(
                        models.Q(("org_id__startswith", "GB-LAE-")),
                        then=models.Value("GB-LAE"),
                    ),
                    models.When(
                        models.Q(("org_id__startswith", "GB-GOR-")),
                        then=models.Value("GB-GOR"),
                    ),
                    default=django.db.models.functions.text.Left(
                        models.F("org_id"),
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.functions.text.StrIndex(
                                models.F("org_id"), models.Value("-")
                            ),
                            "-",
                            models.Value(1),
                        ),
                    ),
                ),
                output_field=models.CharField(max_length=255),
            ),
        ),
    ]
