# Generated by Django 5.0.4 on 2024-04-19 15:47

import django.db.models.expressions
import django.db.models.functions.comparison
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ukgrantmaking", "0020_alter_funder_org_id_schema"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="funder",
            name="name",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Coalesce(
                    "name_manual",
                    models.Case(
                        models.When(
                            name_registered__startswith="The ",
                            then=django.db.models.functions.text.Right(
                                models.F("name_registered"),
                                django.db.models.expressions.CombinedExpression(
                                    django.db.models.functions.text.Length(
                                        models.F("name_registered")
                                    ),
                                    "-",
                                    models.Value(4),
                                ),
                            ),
                        ),
                        default=models.F("name_registered"),
                    ),
                ),
                output_field=models.CharField(max_length=255),
            ),
        ),
        migrations.AddField(
            model_name="funder",
            name="name",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Coalesce(
                    "name_manual",
                    models.Case(
                        models.When(
                            name_registered__startswith="The ",
                            then=django.db.models.functions.text.Right(
                                models.F("name_registered"),
                                django.db.models.expressions.CombinedExpression(
                                    django.db.models.functions.text.Length(
                                        models.F("name_registered")
                                    ),
                                    "-",
                                    models.Value(4),
                                ),
                            ),
                        ),
                        default=models.F("name_registered"),
                    ),
                ),
                output_field=models.CharField(max_length=255),
            ),
        ),
    ]
