# Generated by Django 5.0.4 on 2024-04-24 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ukgrantmaking", "0001_squashed_0021_alter_funder_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="fundertag",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="ukgrantmaking.fundertag",
            ),
        ),
    ]
