# Generated by Django 5.0.4 on 2024-04-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ukgrantmaking", "0022_fundertag_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funder",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="funders", to="ukgrantmaking.fundertag"
            ),
        ),
    ]
