# Generated by Django 5.0.4 on 2024-04-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ukgrantmaking", "0023_alter_funder_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funderyear",
            name="checked_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
