# Generated by Django 5.0.4 on 2024-05-01 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ukgrantmaking", "0024_alter_funderyear_checked_on"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrencyConverter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(max_length=3)),
                ("date", models.DateField()),
                ("rate", models.DecimalField(decimal_places=6, max_digits=16)),
            ],
            options={
                "ordering": ["currency", "-date"],
                "unique_together": {("currency", "date")},
            },
        ),
        migrations.CreateModel(
            name="Grant",
            fields=[
                (
                    "grant_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("currency", models.CharField(default="GBP", max_length=3)),
                (
                    "amount_awarded",
                    models.DecimalField(decimal_places=2, max_digits=16),
                ),
                (
                    "amount_awarded_GBP",
                    models.DecimalField(decimal_places=2, max_digits=16, null=True),
                ),
                ("award_date", models.DateField()),
                ("planned_dates_duration", models.FloatField(blank=True, null=True)),
                ("planned_dates_startDate", models.DateField(blank=True, null=True)),
                ("planned_dates_endDate", models.DateField(blank=True, null=True)),
                (
                    "recipient_organisation_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "recipient_organisation_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "recipient_individual_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "recipient_individual_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "recipient_individual_primary_grant_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "recipient_individual_secondary_grant_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "recipient_individual_grant_purpose",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[
                            ("Organisation", "Organisation"),
                            ("Individual", "Individual"),
                        ],
                        default="Organisation",
                        max_length=50,
                    ),
                ),
                (
                    "funding_organisation_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "funding_organisation_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "funding_organisation_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Grantmaking Organisation", "Grantmaking Organisation"),
                            ("Lottery Distributor", "Lottery Distributor"),
                            ("Central Government", "Central Government"),
                            ("Local Government", "Local Government"),
                            ("Devolved Government", "Devolved Government"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "regrant_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "location_scope",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "grant_programme_title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "publisher_prefix",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "publisher_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("license", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "inclusion",
                    models.CharField(
                        choices=[
                            ("Included", "Included"),
                            ("Excluded", "Excluded"),
                            ("Unsure", "Unsure"),
                        ],
                        default="Unsure",
                        max_length=50,
                    ),
                ),
                (
                    "funder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grants",
                        to="ukgrantmaking.funder",
                    ),
                ),
            ],
        ),
    ]
