# Generated by Django 5.0.4 on 2024-05-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ukgrantmaking", "0027_alter_grant_funding_organisation_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grant",
            name="inclusion",
            field=models.CharField(
                choices=[
                    ("Included", "Included"),
                    ("Unsure", "Unsure"),
                    ("Duplicate grant", "Duplicate grant"),
                    ("Government transfer", "Government transfer"),
                    ("Local Authority Grant", "Local Authority Grant"),
                    ("Overseas government transfer", "Overseas government transfer"),
                ],
                db_index=True,
                default="Unsure",
                max_length=50,
            ),
        ),
    ]
