# Generated by Django 5.0.4 on 2024-05-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ukgrantmaking", "0028_alter_grant_inclusion"),
    ]

    operations = [
        migrations.AddField(
            model_name="grant",
            name="checked_by",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="grant",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
