# Generated by Django 5.0.4 on 2024-05-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ukgrantmaking", "0029_grant_checked_by_grant_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grant",
            name="amount_awarded",
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=16),
        ),
        migrations.AlterField(
            model_name="grant",
            name="amount_awarded_GBP",
            field=models.DecimalField(
                db_index=True, decimal_places=2, max_digits=16, null=True
            ),
        ),
    ]
