# Generated by Django 5.0.4 on 2024-05-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ukgrantmaking", "0030_alter_grant_amount_awarded_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="grant",
            name="recipient_type_manual",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Organisation", "Organisation"),
                    ("Individual", "Individual"),
                    ("Charity", "Charity"),
                    ("Community Interest Company", "Community Interest Company"),
                    ("Education", "Education"),
                    ("Government Department", "Government Department"),
                    ("Local Authority", "Local Authority"),
                    ("Mutual", "Mutual"),
                    ("NDPB", "NDPB"),
                    ("NHS", "NHS"),
                    ("Non-profit Company", "Non-profit Company"),
                    ("Overseas Charity", "Overseas Charity"),
                    ("Overseas Government", "Overseas Government"),
                    ("Parish Council", "Parish Council"),
                    ("Private Company", "Private Company"),
                    ("University", "University"),
                    ("Religious Organisation", "Religious Organisation"),
                ],
                db_index=True,
                default=None,
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="inclusion",
            field=models.CharField(
                choices=[
                    ("Included", "Included"),
                    ("Unsure", "Unsure"),
                    ("Duplicate grant", "Duplicate grant"),
                    ("Government transfer", "Government transfer"),
                    ("Local Authority Grant", "Local Authority Grant"),
                    ("Overseas government transfer", "Overseas government transfer"),
                    ("Private sector grant", "Private sector grant"),
                    ("Grant to education", "Grant to education"),
                ],
                db_index=True,
                default="Unsure",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="recipient_type",
            field=models.CharField(
                choices=[
                    ("Organisation", "Organisation"),
                    ("Individual", "Individual"),
                    ("Charity", "Charity"),
                    ("Community Interest Company", "Community Interest Company"),
                    ("Education", "Education"),
                    ("Government Department", "Government Department"),
                    ("Local Authority", "Local Authority"),
                    ("Mutual", "Mutual"),
                    ("NDPB", "NDPB"),
                    ("NHS", "NHS"),
                    ("Non-profit Company", "Non-profit Company"),
                    ("Overseas Charity", "Overseas Charity"),
                    ("Overseas Government", "Overseas Government"),
                    ("Parish Council", "Parish Council"),
                    ("Private Company", "Private Company"),
                    ("University", "University"),
                    ("Religious Organisation", "Religious Organisation"),
                ],
                db_index=True,
                default="Organisation",
                max_length=50,
            ),
        ),
    ]
