# Generated by Django 5.0.4 on 2024-05-07 14:17

import django.db.models.functions.comparison
import django.db.models.lookups
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ukgrantmaking",
            "0034_alter_funderyear_spending_grant_making_individuals_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="funderyear",
            name="checked",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Q(
                    django.db.models.lookups.IsNull(models.F("checked_by"), False),
                    django.db.models.lookups.IsNull(models.F("notes"), False),
                    django.db.models.lookups.IsNull(models.F("income_manual"), False),
                    django.db.models.lookups.IsNull(models.F("spending_manual"), False),
                    django.db.models.lookups.IsNull(
                        models.F("spending_charitable_manual"), False
                    ),
                    django.db.models.lookups.IsNull(
                        models.F("spending_grant_making_individuals_manual"), False
                    ),
                    django.db.models.lookups.IsNull(
                        models.F("spending_grant_making_institutions_manual"), False
                    ),
                    django.db.models.lookups.IsNull(
                        models.F("total_net_assets_manual"), False
                    ),
                    django.db.models.lookups.IsNull(models.F("funds_manual"), False),
                    django.db.models.lookups.IsNull(
                        models.F("funds_endowment_manual"), False
                    ),
                    django.db.models.lookups.IsNull(
                        models.F("funds_restricted_manual"), False
                    ),
                    django.db.models.lookups.IsNull(
                        models.F("funds_unrestricted_manual"), False
                    ),
                    django.db.models.lookups.IsNull(
                        models.F("employees_manual"), False
                    ),
                    _connector="OR",
                ),
                output_field=models.BooleanField(),
            ),
        ),
    ]
