# Generated by Django 5.0.4 on 2024-05-07 14:17

import django.db.models.functions.comparison
import django.db.models.lookups
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ukgrantmaking",
            "0034_alter_funderyear_spending_grant_making_individuals_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="funderyear",
            name="checked",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.lookups.IsNull(
                    django.db.models.functions.comparison.Coalesce(
                        "checked_by",
                        "notes",
                        "income_manual",
                        "spending_manual",
                        "spending_charitable_manual",
                        "spending_grant_making_individuals_manual",
                        "spending_grant_making_institutions_manual",
                        "total_net_assets_manual",
                        "funds_manual",
                        "funds_endowment_manual",
                        "funds_restricted_manual",
                        "funds_unrestricted_manual",
                        "employees_manual",
                        output_field=models.BooleanField(),
                    ),
                    False,
                ),
                output_field=models.BooleanField(),
            ),
        ),
    ]
