# Generated by Django 5.0.6 on 2024-05-15 15:01

import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.comparison
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ukgrantmaking", "0035_funderyear_checked"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrantRecipient",
            fields=[
                (
                    "recipient_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name_registered", models.CharField(max_length=255)),
                (
                    "name_manual",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "name",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.comparison.Coalesce(
                            "name_manual",
                            models.Case(
                                models.When(
                                    name_registered__startswith="The ",
                                    then=django.db.models.functions.text.Right(
                                        models.F("name_registered"),
                                        django.db.models.expressions.CombinedExpression(
                                            django.db.models.functions.text.Length(
                                                models.F("name_registered")
                                            ),
                                            "-",
                                            models.Value(4),
                                        ),
                                    ),
                                ),
                                default=models.F("name_registered"),
                            ),
                        ),
                        output_field=models.CharField(max_length=255),
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Organisation", "Organisation"),
                            ("Individual", "Individual"),
                            ("Charity", "Charity"),
                            (
                                "Community Interest Company",
                                "Community Interest Company",
                            ),
                            ("Education", "Education"),
                            ("Government Department", "Government Department"),
                            ("Local Authority", "Local Authority"),
                            ("Mutual", "Mutual"),
                            ("NDPB", "NDPB"),
                            ("NHS", "NHS"),
                            ("Non-profit Company", "Non-profit Company"),
                            ("Overseas Charity", "Overseas Charity"),
                            ("Overseas Government", "Overseas Government"),
                            ("Private Company", "Private Company"),
                            ("University", "University"),
                            ("Religious Organisation", "Religious Organisation"),
                            ("Sports Club", "Sports Club"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date_registered", models.DateField(blank=True, null=True)),
                ("date_removed", models.DateField(blank=True, null=True)),
                ("active", models.BooleanField(blank=True, null=True)),
                (
                    "scale_registered",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Local", "Local"),
                            ("National", "National"),
                            ("Overseas", "Overseas"),
                            ("National and Overseas", "National and Overseas"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "scale_manual",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Local", "Local"),
                            ("National", "National"),
                            ("Overseas", "Overseas"),
                            ("National and Overseas", "National and Overseas"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "scale",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.comparison.Coalesce(
                            "scale_manual", "scale_registered"
                        ),
                        output_field=models.CharField(
                            blank=True,
                            choices=[
                                ("Local", "Local"),
                                ("National", "National"),
                                ("Overseas", "Overseas"),
                                ("National and Overseas", "National and Overseas"),
                            ],
                            max_length=50,
                            null=True,
                        ),
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="funder",
            name="active",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="funder",
            name="date_of_removal",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="grant",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grants",
                to="ukgrantmaking.grantrecipient",
            ),
        ),
        migrations.CreateModel(
            name="GrantRecipientYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("financial_year_end", models.DateField()),
                ("financial_year_start", models.DateField(blank=True, null=True)),
                (
                    "financial_year",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("2029-30", "2029-30"),
                            ("2028-29", "2028-29"),
                            ("2027-28", "2027-28"),
                            ("2026-27", "2026-27"),
                            ("2025-26", "2025-26"),
                            ("2024-25", "2024-25"),
                            ("2023-24", "2023-24"),
                            ("2022-23", "2022-23"),
                            ("2021-22", "2021-22"),
                            ("2020-21", "2020-21"),
                            ("2019-20", "2019-20"),
                            ("2018-19", "2018-19"),
                            ("2017-18", "2017-18"),
                            ("2016-17", "2016-17"),
                            ("2015-16", "2015-16"),
                            ("2014-15", "2014-15"),
                            ("2013-14", "2013-14"),
                            ("2012-13", "2012-13"),
                            ("2011-12", "2011-12"),
                            ("2010-11", "2010-11"),
                            ("2009-10", "2009-10"),
                            ("2008-09", "2008-09"),
                            ("2007-08", "2007-08"),
                            ("2006-07", "2006-07"),
                            ("2005-06", "2005-06"),
                            ("2004-05", "2004-05"),
                            ("2003-04", "2003-04"),
                            ("2002-03", "2002-03"),
                            ("2001-02", "2001-02"),
                            ("2000-01", "2000-01"),
                        ],
                        db_index=True,
                        max_length=9,
                        null=True,
                    ),
                ),
                (
                    "income_registered",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "income_manual",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "income",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.comparison.Coalesce(
                            "income_manual", "income_registered"
                        ),
                        output_field=models.BigIntegerField(),
                    ),
                ),
                (
                    "spending_registered",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "spending_manual",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "spending",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.comparison.Coalesce(
                            "spending_manual", "spending_registered"
                        ),
                        output_field=models.BigIntegerField(),
                    ),
                ),
                ("employees_registered", models.IntegerField(blank=True, null=True)),
                ("employees_manual", models.IntegerField(blank=True, null=True)),
                (
                    "employees",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.comparison.Coalesce(
                            "employees_manual", "employees_registered"
                        ),
                        output_field=models.BigIntegerField(),
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ukgrantmaking.grantrecipient",
                    ),
                ),
            ],
        ),
    ]
