# Generated by Django 5.0.6 on 2024-05-15 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "ukgrantmaking",
            "0036_grantrecipient_funder_active_funder_date_of_removal_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="grantrecipient",
            old_name="date_registered",
            new_name="date_of_registration",
        ),
        migrations.RenameField(
            model_name="grantrecipient",
            old_name="date_removed",
            new_name="date_of_removal",
        ),
    ]
