# Generated by Django 5.0.6 on 2024-05-15 21:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ukgrantmaking", "0038_grantrecipient_org_id_schema"),
    ]

    operations = [
        migrations.RenameField(
            model_name="grant",
            old_name="regrant_type",
            new_name="regrant_type_registered",
        ),
    ]
