# Generated by Django 5.0.6 on 2024-05-15 21:57

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ukgrantmaking", "0039_rename_regrant_type_grant_regrant_type_registered"),
    ]

    operations = [
        migrations.AddField(
            model_name="grant",
            name="regrant_type_manual",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="grant",
            name="regrant_type",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Coalesce(
                    "regrant_type_manual", "regrant_type_registered"
                ),
                output_field=models.CharField(blank=True, max_length=255, null=True),
            ),
        ),
    ]
