# Generated by Django 5.0.6 on 2024-05-15 22:12

import django.db.models.expressions
import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ukgrantmaking", "0040_grant_regrant_type_manual_grant_regrant_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="grant",
            name="annual_amount",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Case(
                    models.When(
                        planned_dates_duration__isnull=False,
                        then=django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                django.db.models.functions.comparison.Cast(
                                    models.F("amount_awarded_GBP"), models.FloatField()
                                ),
                                "/",
                                models.F("planned_dates_duration"),
                            ),
                            "*",
                            models.Value(12),
                        ),
                    ),
                    default=django.db.models.functions.comparison.Cast(
                        models.F("amount_awarded_GBP"), models.FloatField()
                    ),
                ),
                output_field=models.DecimalField(decimal_places=2, max_digits=16),
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="location_scope",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GLS010", "Global"),
                    ("GLS020", "Supranational"),
                    ("GLS030", "National"),
                    ("GLS040", "Subnational region"),
                    ("GLS050", "Local authority"),
                    ("GLS060", "Local area"),
                    ("GLS099", "Undefined"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="regrant_type_manual",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FRG010", "Common Regrant"),
                    ("FRG020", "Transfer to intermediary"),
                    ("FRG030", "Match funding"),
                    ("FRG040", "Funder collaboration"),
                    ("FRG050", "Fiscal sponsor"),
                    ("FRG060", "Endowment"),
                    ("FRG070", "Multipurpose"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="regrant_type_registered",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FRG010", "Common Regrant"),
                    ("FRG020", "Transfer to intermediary"),
                    ("FRG030", "Match funding"),
                    ("FRG040", "Funder collaboration"),
                    ("FRG050", "Fiscal sponsor"),
                    ("FRG060", "Endowment"),
                    ("FRG070", "Multipurpose"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
