# Generated by Django 5.0.6 on 2024-05-16 08:17

import django.db.models.expressions
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ukgrantmaking",
            "0041_grant_annual_amount_alter_grant_location_scope_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grantrecipient",
            name="org_id_schema",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Case(
                    models.When(
                        models.Q(("recipient_id__startswith", "UKG-")),
                        then=models.Value("UKG"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "360G-")),
                        then=models.Value("UKG"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "GB-CHC-")),
                        then=models.Value("GB-CHC"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "GB-COH-")),
                        then=models.Value("GB-COH"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "GB-SC-")),
                        then=models.Value("GB-SC"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "GB-NIC-")),
                        then=models.Value("GB-NIC"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "GB-LAE-")),
                        then=models.Value("GB-LAE"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "GB-GOR-")),
                        then=models.Value("GB-GOR"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "GB-SHPE-")),
                        then=models.Value("GB-SHPE"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "GB-NHS-")),
                        then=models.Value("GB-NHS"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "GB-LAS-")),
                        then=models.Value("GB-LAS"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "GB-PLA-")),
                        then=models.Value("GB-PLA"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "GB-LANI-")),
                        then=models.Value("GB-LANI"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "US-EIN-")),
                        then=models.Value("US-EIN"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "XI-ROR-")),
                        then=models.Value("XI-ROR"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "XI-PB-")),
                        then=models.Value("XI-PB"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "GB-WALEDU-")),
                        then=models.Value("GB-WALEDU"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "GB-NIEDU-")),
                        then=models.Value("GB-NIEDU"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "GB-SCOTEDU-")),
                        then=models.Value("GB-SCOTEDU"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "GB-UKPRN-")),
                        then=models.Value("GB-UKPRN"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "GB-REV-")),
                        then=models.Value("GB-REV"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "GB-MPR-")),
                        then=models.Value("GB-MPR"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "GB-EDU-")),
                        then=models.Value("GB-EDU"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "GB-HESA-")),
                        then=models.Value("GB-HESA"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "AT-ZVR-")),
                        then=models.Value("AT-ZVR"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "BE-BCE_KBO-")),
                        then=models.Value("BE-BCE_KBO"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "CH-FDJP-")),
                        then=models.Value("CH-FDJP"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "CHC-")),
                        then=models.Value("GB-CHC"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "DE-CR-")),
                        then=models.Value("DE-CR"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "GG-RCE-")),
                        then=models.Value("GG-RCE"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "IE-CRO-")),
                        then=models.Value("IE-CRO"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "IL-RA-")),
                        then=models.Value("IL-RA"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "IM-CR-")),
                        then=models.Value("IM-CR"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "IM-GR-")),
                        then=models.Value("IM-GR"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "JE-JCR-")),
                        then=models.Value("JE-JCR"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "ZA-NPO-")),
                        then=models.Value("ZA-NPO"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "tnlcomfund-org-")),
                        then=models.Value("tnlcomfund-org"),
                    ),
                    default=django.db.models.functions.text.Left(
                        models.F("recipient_id"),
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.functions.text.StrIndex(
                                models.F("recipient_id"), models.Value("-")
                            ),
                            "-",
                            models.Value(1),
                        ),
                    ),
                ),
                output_field=models.CharField(max_length=255),
            ),
        ),
        migrations.AddField(
            model_name="grantrecipient",
            name="org_id_schema",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Case(
                    models.When(
                        models.Q(("recipient_id__startswith", "UKG-")),
                        then=models.Value("UKG"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "360G-")),
                        then=models.Value("UKG"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "GB-CHC-")),
                        then=models.Value("GB-CHC"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "GB-COH-")),
                        then=models.Value("GB-COH"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "GB-SC-")),
                        then=models.Value("GB-SC"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "GB-NIC-")),
                        then=models.Value("GB-NIC"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "GB-LAE-")),
                        then=models.Value("GB-LAE"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "GB-GOR-")),
                        then=models.Value("GB-GOR"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "GB-SHPE-")),
                        then=models.Value("GB-SHPE"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "GB-NHS-")),
                        then=models.Value("GB-NHS"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "GB-LAS-")),
                        then=models.Value("GB-LAS"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "GB-PLA-")),
                        then=models.Value("GB-PLA"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "GB-LANI-")),
                        then=models.Value("GB-LANI"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "US-EIN-")),
                        then=models.Value("US-EIN"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "XI-ROR-")),
                        then=models.Value("XI-ROR"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "XI-PB-")),
                        then=models.Value("XI-PB"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "GB-WALEDU-")),
                        then=models.Value("GB-WALEDU"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "GB-NIEDU-")),
                        then=models.Value("GB-NIEDU"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "GB-SCOTEDU-")),
                        then=models.Value("GB-SCOTEDU"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "GB-UKPRN-")),
                        then=models.Value("GB-UKPRN"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "GB-REV-")),
                        then=models.Value("GB-REV"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "GB-MPR-")),
                        then=models.Value("GB-MPR"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "GB-EDU-")),
                        then=models.Value("GB-EDU"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "GB-HESA-")),
                        then=models.Value("GB-HESA"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "AT-ZVR-")),
                        then=models.Value("AT-ZVR"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "BE-BCE_KBO-")),
                        then=models.Value("BE-BCE_KBO"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "CH-FDJP-")),
                        then=models.Value("CH-FDJP"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "CHC-")),
                        then=models.Value("GB-CHC"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "DE-CR-")),
                        then=models.Value("DE-CR"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "GG-RCE-")),
                        then=models.Value("GG-RCE"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "IE-CRO-")),
                        then=models.Value("IE-CRO"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "IL-RA-")),
                        then=models.Value("IL-RA"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "IM-CR-")),
                        then=models.Value("IM-CR"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "IM-GR-")),
                        then=models.Value("IM-GR"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "JE-JCR-")),
                        then=models.Value("JE-JCR"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "ZA-NPO-")),
                        then=models.Value("ZA-NPO"),
                    ),
                    models.When(
                        models.Q(("recipient_id__startswith", "tnlcomfund-org-")),
                        then=models.Value("tnlcomfund-org"),
                    ),
                    default=django.db.models.functions.text.Left(
                        models.F("recipient_id"),
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.functions.text.StrIndex(
                                models.F("recipient_id"), models.Value("-")
                            ),
                            "-",
                            models.Value(1),
                        ),
                    ),
                ),
                output_field=models.CharField(max_length=255),
            ),
        ),
    ]
