# Generated by Django 5.0.6 on 2024-05-16 11:14

import django.db.models.aggregates
import django.db.models.expressions
import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ukgrantmaking", "0042_alter_grantrecipient_org_id_schema"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grant",
            name="annual_amount",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Case(
                    models.When(
                        planned_dates_duration__isnull=False,
                        then=django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                django.db.models.functions.comparison.Cast(
                                    models.F("amount_awarded_GBP"), models.FloatField()
                                ),
                                "/",
                                django.db.models.functions.Greatest(
                                    models.F("planned_dates_duration"),
                                    models.Value(12, models.FloatField()),
                                ),
                            ),
                            "*",
                            models.Value(12),
                        ),
                    ),
                    default=django.db.models.functions.comparison.Cast(
                        models.F("amount_awarded_GBP"), models.FloatField()
                    ),
                ),
                output_field=models.DecimalField(decimal_places=2, max_digits=16),
            ),
        ),
        migrations.AddField(
            model_name="grant",
            name="annual_amount",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Case(
                    models.When(
                        planned_dates_duration__isnull=False,
                        then=django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                django.db.models.functions.comparison.Cast(
                                    models.F("amount_awarded_GBP"), models.FloatField()
                                ),
                                "/",
                                django.db.models.functions.Greatest(
                                    models.F("planned_dates_duration"),
                                    models.Value(12, models.FloatField()),
                                ),
                            ),
                            "*",
                            models.Value(12),
                        ),
                    ),
                    default=django.db.models.functions.comparison.Cast(
                        models.F("amount_awarded_GBP"), models.FloatField()
                    ),
                ),
                output_field=models.DecimalField(decimal_places=2, max_digits=16),
            ),
        ),
    ]
