# Generated by Django 5.0.6 on 2024-05-20 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ukgrantmaking", "0043_alter_grant_annual_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grant",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grants",
                to="ukgrantmaking.grantrecipient",
            ),
        ),
    ]
