# Generated by Django 5.0.6 on 2024-05-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ukgrantmaking", "0044_alter_grant_recipient"),
    ]

    operations = [
        migrations.AddField(
            model_name="grant",
            name="beneficiary_location_ctry",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="grant",
            name="beneficiary_location_rgn",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="grant",
            name="recipient_location_ctry",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="grant",
            name="recipient_location_rgn",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="grantrecipient",
            name="ctry_aoo",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="grantrecipient",
            name="ctry_hq",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="grantrecipient",
            name="how",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="grantrecipient",
            name="london_aoo",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="grantrecipient",
            name="london_hq",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="grantrecipient",
            name="rgn_aoo",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="grantrecipient",
            name="rgn_hq",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="grantrecipient",
            name="what",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="grantrecipient",
            name="who",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
