# Generated by Django 5.0.6 on 2024-11-04 19:31

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ukgrantmaking", "0046_alter_funderyear_date_added"),
    ]

    operations = [
        migrations.AddField(
            model_name="fundernote",
            name="resolved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="fundernote",
            name="note",
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name="funderyear",
            name="notes",
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="grant",
            name="notes",
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
