# Generated by Django 5.0.6 on 2024-11-12 10:47

from django.db import migrations, models

FINANCIAL_YEARS = [
    "2029-30",
    "2028-29",
    "2027-28",
    "2026-27",
    "2025-26",
    "2024-25",
    "2023-24",
    "2022-23",
    "2021-22",
    "2020-21",
    "2019-20",
    "2018-19",
    "2017-18",
    "2016-17",
    "2015-16",
    "2014-15",
    "2013-14",
    "2012-13",
    "2011-12",
    "2010-11",
    "2009-10",
    "2008-09",
    "2007-08",
    "2006-07",
    "2005-06",
    "2004-05",
    "2003-04",
    "2002-03",
    "2001-02",
    "2000-01",
]


def create_financial_years(apps, schema_editor):
    FinancialYear = apps.get_model("ukgrantmaking", "FinancialYear")
    for fy in FINANCIAL_YEARS:
        first_year = int(fy[:4])
        last_year = first_year + 1
        fy_obj = FinancialYear(
            fy=fy,
            funders_start_date=f"{first_year}-05-01",
            funders_end_date=f"{last_year}-04-30",
            grants_start_date=f"{first_year}-04-01",
            grants_end_date=f"{last_year}-03-31",
            status="Closed",
        )
        fy_obj.save()

    # set 2023-24 as current
    FinancialYear.objects.filter(fy="2022-23").update(current=True)

    # set later years as future
    FinancialYear.objects.filter(
        fy__in=[
            "2029-30",
            "2028-29",
            "2027-28",
            "2026-27",
            "2025-26",
            "2024-25",
            "2023-24",
        ]
    ).update(status="Future")


class Migration(migrations.Migration):
    dependencies = [
        ("ukgrantmaking", "0047_fundernote_resolved_alter_fundernote_note_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialYear",
            fields=[
                (
                    "fy",
                    models.CharField(
                        choices=[
                            ("2029-30", "2029-30"),
                            ("2028-29", "2028-29"),
                            ("2027-28", "2027-28"),
                            ("2026-27", "2026-27"),
                            ("2025-26", "2025-26"),
                            ("2024-25", "2024-25"),
                            ("2023-24", "2023-24"),
                            ("2022-23", "2022-23"),
                            ("2021-22", "2021-22"),
                            ("2020-21", "2020-21"),
                            ("2019-20", "2019-20"),
                            ("2018-19", "2018-19"),
                            ("2017-18", "2017-18"),
                            ("2016-17", "2016-17"),
                            ("2015-16", "2015-16"),
                            ("2014-15", "2014-15"),
                            ("2013-14", "2013-14"),
                            ("2012-13", "2012-13"),
                            ("2011-12", "2011-12"),
                            ("2010-11", "2010-11"),
                            ("2009-10", "2009-10"),
                            ("2008-09", "2008-09"),
                            ("2007-08", "2007-08"),
                            ("2006-07", "2006-07"),
                            ("2005-06", "2005-06"),
                            ("2004-05", "2004-05"),
                            ("2003-04", "2003-04"),
                            ("2002-03", "2002-03"),
                            ("2001-02", "2001-02"),
                            ("2000-01", "2000-01"),
                        ],
                        default="2022-23",
                        max_length=7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("funders_start_date", models.DateField()),
                ("funders_end_date", models.DateField()),
                ("grants_start_date", models.DateField()),
                ("grants_end_date", models.DateField()),
                ("current", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Open", "Open"),
                            ("Closed", "Closed"),
                            ("Future", "Future"),
                        ],
                        default="Closed",
                        max_length=6,
                    ),
                ),
            ],
        ),
        migrations.RunPython(create_financial_years),
    ]
