# Generated by Django 5.0.6 on 2024-11-12 11:01

from django.db import migrations, models
from django.utils.text import slugify


def slugify_fundertags(apps, schema_editor):
    FunderTag = apps.get_model("ukgrantmaking", "FunderTag")
    for funder_tag in FunderTag.objects.all():
        funder_tag.slug = slugify(funder_tag.tag)
        funder_tag.save()


def slugify_fundertag_parents(apps, schema_editor):
    FunderTag = apps.get_model("ukgrantmaking", "FunderTag")
    for funder_tag in FunderTag.objects.filter(parent__isnull=False):
        funder_tag.parent_id = slugify(funder_tag.parent_id)
        funder_tag.save()


def slugify_funder_tags(apps, schema_editor):
    Funder = apps.get_model("ukgrantmaking", "Funder")
    for funder in Funder.objects.filter():
        for tag in funder.tags.through.objects.all():
            tag.tag_ig = slugify(tag.tag_ig)
            tag.save()


class Migration(migrations.Migration):
    dependencies = [
        ("ukgrantmaking", "0048_financialyear"),
    ]

    operations = [
        migrations.AddField(
            model_name="fundertag",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.RunPython(
            slugify_fundertags, reverse_code=migrations.RunPython.noop
        ),
        migrations.AddField(
            model_name="funder",
            name="tag_backup",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RunSQL(
            """update ukgrantmaking_funder
set tag_backup = tags_concat
from (
    select funder_id, string_agg(t.slug, ';') as tags_concat
    from ukgrantmaking_funder_tags ft
        INNER JOIN ukgrantmaking_fundertag t
            ON ft.fundertag_id = t.tag
    group by 1
) a
where a.funder_id = org_id""",
        ),
        migrations.RemoveField(
            model_name="funder",
            name="tags",
        ),
        migrations.AlterField(
            model_name="fundertag",
            name="parent",
            field=models.SlugField(max_length=255),
        ),
        migrations.RunPython(
            slugify_fundertag_parents, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="fundertag",
            name="tag",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="fundertag",
            name="slug",
            field=models.SlugField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="fundertag",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.CASCADE,
                related_name="children",
                to="ukgrantmaking.fundertag",
            ),
        ),
        migrations.RunPython(
            slugify_funder_tags, reverse_code=migrations.RunPython.noop
        ),
    ]
