# Generated by Django 5.0.6 on 2024-11-12 12:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ukgrantmaking", "0049_fundertag_slug"),
    ]

    operations = []
