# Generated by Django 5.0.6 on 2024-11-12 12:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ukgrantmaking", "0050_funder_tag_backup"),
    ]

    operations = []
