# Generated by Django 5.0.6 on 2024-11-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ukgrantmaking", "0051_remove_funder_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="funder",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="funders", to="ukgrantmaking.fundertag"
            ),
        ),
    ]
