# Generated by Django 5.0.6 on 2024-11-12 12:15

from django.db import migrations


def convert_tags_from_backup(apps, schema_editor):
    Funder = apps.get_model("ukgrantmaking", "Funder")
    FunderTag = apps.get_model("ukgrantmaking", "FunderTag")

    for funder in Funder.objects.all():
        if funder.tag_backup:
            tags = funder.tag_backup.split(";")
            funder.tags.set(FunderTag.objects.filter(slug__in=tags))
            funder.save()


class Migration(migrations.Migration):
    dependencies = [
        ("ukgrantmaking", "0052_funder_tags"),
    ]

    operations = [
        migrations.RunPython(
            convert_tags_from_backup, reverse_code=migrations.RunPython.noop
        ),
    ]
