# Generated by Django 5.0.6 on 2024-11-12 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ukgrantmaking", "0055_funderfinancialyear"),
    ]

    operations = [
        migrations.AddField(
            model_name="funder",
            name="successor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="predecessors",
                to="ukgrantmaking.funder",
            ),
        ),
    ]
