# Generated by Django 5.0.6 on 2024-11-14 11:21

import django.db.models.deletion
import markdownx.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ukgrantmaking",
            "0057_rename_spending_grant_making_institutions_360giving_funderyear_spending_grant_making_institutions_un",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="funderfinancialyear",
            name="checked",
            field=models.CharField(
                blank=True,
                choices=[("Unchecked", "Unchecked"), ("Checked", "Checked")],
                db_index=True,
                default="Unchecked",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="funderfinancialyear",
            name="checked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="funderfinancialyear",
            name="checked_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="funderfinancialyear",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="funderfinancialyear",
            name="date_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="funderfinancialyear",
            name="notes",
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="funderfinancialyear",
            name="segment_checked",
            field=models.CharField(
                blank=True,
                choices=[("Unchecked", "Unchecked"), ("Checked", "Checked")],
                db_index=True,
                default="Unchecked",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="funderyear",
            name="funder_financial_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="financial_years",
                to="ukgrantmaking.funderfinancialyear",
            ),
        ),
    ]
