# Generated by Django 5.0.6 on 2024-11-14 11:26

from django.db import migrations

UPDATE_SQL = """
UPDATE ukgrantmaking_funderyear
SET funder_financial_year_id = ukgrantmaking_funderfinancialyear.id
FROM ukgrantmaking_funderfinancialyear
WHERE ukgrantmaking_funderyear.funder_id = ukgrantmaking_funderfinancialyear.funder_id
    AND ukgrantmaking_funderyear.financial_year = ukgrantmaking_funderfinancialyear.financial_year_id;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("ukgrantmaking", "0058_funderfinancialyear_checked_and_more"),
    ]

    operations = [
        # migrations.RunSQL(UPDATE_SQL, reverse_sql=""),
    ]
