# Generated by Django 5.0.6 on 2024-11-14 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ukgrantmaking", "0059_auto_20241114_1126"),
    ]

    operations = [
        migrations.CreateModel(
            name="CleaningStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("Grant", "Grant"), ("Grantmaker", "Grantmaker")],
                        default="Grantmaker",
                        max_length=50,
                    ),
                ),
                (
                    "date_added",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CleaningStatusQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field", models.CharField(max_length=50)),
                (
                    "comparison",
                    models.CharField(
                        choices=[
                            ("Equal", "Equal"),
                            ("Not Equal", "Not Equal"),
                            ("Greater Than", "Greater Than"),
                            ("Less Than", "Less Than"),
                            ("Greater Than or Equal", "Greater Than or Equal"),
                            ("Less Than or Equal", "Less Than or Equal"),
                            ("Contains", "Contains"),
                            ("Not Contains", "Not Contains"),
                            ("Starts With", "Starts With"),
                            ("Ends With", "Ends With"),
                            ("Is Null", "Is Null"),
                            ("Is Not Null", "Is Not Null"),
                        ],
                        default="Equal",
                        max_length=50,
                    ),
                ),
                ("value", models.CharField(max_length=50)),
                ("active", models.BooleanField(default=True)),
                (
                    "date_added",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "cleaning_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ukgrantmaking.cleaningstatus",
                    ),
                ),
            ],
        ),
    ]
