# Generated by Django 5.0.6 on 2024-11-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ukgrantmaking", "0060_cleaningstatus_cleaningstatusquery"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cleaningstatus",
            options={"ordering": ["name"], "verbose_name_plural": "Cleaning Statuses"},
        ),
        migrations.AddField(
            model_name="cleaningstatus",
            name="n",
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name="cleaningstatus",
            name="sort_by",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
