# Generated by Django 5.0.6 on 2024-11-14 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ukgrantmaking", "0063_alter_cleaningstatus_sort_by_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cleaningstatus",
            options={
                "ordering": ["name"],
                "verbose_name": "Cleaning check",
                "verbose_name_plural": "Cleaning checks",
            },
        ),
    ]
