# Generated by Django 5.0.6 on 2024-11-14 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ukgrantmaking", "0065_alter_funderyear_spending_grant_making_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="funderyear",
            options={"ordering": ["financial_year", "-financial_year_end"]},
        ),
        migrations.AlterUniqueTogether(
            name="funderyear",
            unique_together={("financial_year", "financial_year_end")},
        ),
        migrations.AddField(
            model_name="grant",
            name="financial_year",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grants",
                to="ukgrantmaking.financialyear",
            ),
        ),
        migrations.AlterField(
            model_name="funderyear",
            name="financial_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="financial_years",
                to="ukgrantmaking.funderfinancialyear",
            ),
        ),
        migrations.AlterField(
            model_name="grantrecipientyear",
            name="financial_year",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipient_years",
                to="ukgrantmaking.financialyear",
            ),
        ),
        migrations.RemoveField(
            model_name="funderyear",
            name="funder",
        ),
        migrations.RemoveField(
            model_name="funderyear",
            name="funder_financial_year",
        ),
    ]
