# Generated by Django 5.0.6 on 2024-11-15 07:20

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ukgrantmaking", "0067_alter_funder_latest_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="grant",
            name="recipient_type_registered",
            field=models.CharField(
                choices=[
                    ("Organisation", "Organisation"),
                    ("Individual", "Individual"),
                    ("Charity", "Charity"),
                    ("Community Interest Company", "Community Interest Company"),
                    ("Education", "Education"),
                    ("Government Department", "Government Department"),
                    ("Local Authority", "Local Authority"),
                    ("Mutual", "Mutual"),
                    ("NDPB", "NDPB"),
                    ("NHS", "NHS"),
                    ("Non-profit Company", "Non-profit Company"),
                    ("Overseas Charity", "Overseas Charity"),
                    ("Overseas Government", "Overseas Government"),
                    ("Private Company", "Private Company"),
                    ("University", "University"),
                    ("Religious Organisation", "Religious Organisation"),
                    ("Sports Club", "Sports Club"),
                ],
                db_index=True,
                default="Organisation",
                max_length=50,
            ),
        ),
        migrations.RemoveField(
            model_name="grant",
            name="recipient_type",
        ),
        migrations.AddField(
            model_name="grant",
            name="recipient_type",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Coalesce(
                    "recipient_type_manual", "recipient_type_registered"
                ),
                output_field=models.CharField(blank=True, max_length=255, null=True),
            ),
        ),
    ]
