# Generated by Django 5.0.6 on 2024-11-15 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ukgrantmaking", "0069_alter_grant_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundernote",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="funder_notes_added",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
