# Generated by Django 5.0.6 on 2024-11-16 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ukgrantmaking", "0071_alter_cleaningstatus_sort_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funder",
            name="latest_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="funder_latest_year",
                to="ukgrantmaking.funderfinancialyear",
            ),
        ),
    ]
