# Generated by Django 5.0.6 on 2024-11-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ukgrantmaking", "0072_alter_funder_latest_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="funderfinancialyear",
            name="segment_checked",
        ),
        migrations.AddField(
            model_name="funder",
            name="status",
            field=models.CharField(
                choices=[
                    ("Unchecked", "Unchecked"),
                    ("Checked", "Checked"),
                    ("New", "New"),
                ],
                db_index=True,
                default="Unchecked",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="funderfinancialyear",
            name="checked",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Unchecked", "Unchecked"),
                    ("Checked", "Checked"),
                    ("New", "New"),
                ],
                db_index=True,
                default="Unchecked",
                max_length=50,
                null=True,
            ),
        ),
    ]
