# Generated by Django 5.0.6 on 2024-11-18 11:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ukgrantmaking", "0075_alter_funderyear_spending_grant_making_institutions"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="funderfinancialyear",
            unique_together={("funder", "financial_year")},
        ),
    ]
