# Generated by Django 5.0.6 on 2024-11-18 11:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ukgrantmaking", "0076_alter_funderfinancialyear_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="funder",
            options={"ordering": ["-latest_year__spending_grant_making"]},
        ),
        migrations.RemoveField(
            model_name="funder",
            name="latest_grantmaking",
        ),
    ]
