# Generated by Django 5.0.6 on 2024-11-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ukgrantmaking", "0080_funderyear_original_funder_financial_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funderyear",
            name="financial_year_end",
            field=models.DateField(db_index=True),
        ),
    ]
