# Generated by Django 5.0.6 on 2024-11-18 22:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ukgrantmaking", "0081_alter_funderyear_financial_year_end"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="grantrecipientyear",
            unique_together={("recipient", "financial_year_end")},
        ),
    ]
