# Generated by Django 5.0.6 on 2024-11-19 01:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ukgrantmaking", "0082_alter_grantrecipientyear_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="funderyear",
            unique_together={
                (
                    "funder_financial_year",
                    "financial_year_end",
                    "original_funder_financial_year",
                )
            },
        ),
    ]
