# Generated by Django 5.0.6 on 2024-11-19 16:57

from django.db import migrations, models


def update_general_grantmaker(apps, schema_editor):
    Funder = apps.get_model("ukgrantmaking", "Funder")
    Funder.objects.filter(segment="General grantmaker").update(
        segment="General foundation"
    )

    FunderFinancialYear = apps.get_model("ukgrantmaking", "FunderFinancialYear")
    FunderFinancialYear.objects.filter(segment="General grantmaker").update(
        segment="General foundation"
    )


def update_general_foundation(apps, schema_editor):
    Funder = apps.get_model("ukgrantmaking", "Funder")
    Funder.objects.filter(segment="General foundation").update(
        segment="General grantmaker"
    )

    FunderFinancialYear = apps.get_model("ukgrantmaking", "FunderFinancialYear")
    FunderFinancialYear.objects.filter(segment="General foundation").update(
        segment="General grantmaker"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("ukgrantmaking", "0086_alter_cleaningstatus_sort_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funder",
            name="status",
            field=models.CharField(
                choices=[
                    ("Unchecked", "Unchecked"),
                    ("Checked", "Checked"),
                    ("New", "New"),
                    ("For Review", "For Review"),
                ],
                db_index=True,
                default="Unchecked",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="funderfinancialyear",
            name="checked",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Unchecked", "Unchecked"),
                    ("Checked", "Checked"),
                    ("New", "New"),
                    ("For Review", "For Review"),
                ],
                db_index=True,
                default="Unchecked",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="funder",
            name="segment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Donor Advised Fund", "Donor Advised Fund"),
                    ("Wellcome Trust", "Wellcome Trust"),
                    ("Charity", "Charity"),
                    ("Lottery Distributor", "Lottery Distributor"),
                    ("Arms Length Body", "Arms Length Body"),
                    ("Corporate Foundation", "Corporate Foundation"),
                    ("Family Foundation", "Family Foundation"),
                    ("Fundraising Grantmaker", "Fundraising Grantmaker"),
                    ("General grantmaker", "General grantmaker"),
                    ("General foundation", "General foundation"),
                    ("Member/Trade Funded", "Member/Trade Funded"),
                    ("NHS/Hospital Foundation", "NHS/Hospital Foundation"),
                    ("Government/Lottery Endowed", "Government/Lottery Endowed"),
                    ("Small grantmaker", "Small grantmaker"),
                    ("Community Foundation", "Community Foundation"),
                    ("Local", "Local"),
                    ("Central", "Central"),
                    ("Devolved", "Devolved"),
                ],
                db_index=True,
                default="General foundation",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="funderfinancialyear",
            name="segment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Donor Advised Fund", "Donor Advised Fund"),
                    ("Wellcome Trust", "Wellcome Trust"),
                    ("Charity", "Charity"),
                    ("Lottery Distributor", "Lottery Distributor"),
                    ("Arms Length Body", "Arms Length Body"),
                    ("Corporate Foundation", "Corporate Foundation"),
                    ("Family Foundation", "Family Foundation"),
                    ("Fundraising Grantmaker", "Fundraising Grantmaker"),
                    ("General grantmaker", "General grantmaker"),
                    ("General foundation", "General foundation"),
                    ("Member/Trade Funded", "Member/Trade Funded"),
                    ("NHS/Hospital Foundation", "NHS/Hospital Foundation"),
                    ("Government/Lottery Endowed", "Government/Lottery Endowed"),
                    ("Small grantmaker", "Small grantmaker"),
                    ("Community Foundation", "Community Foundation"),
                    ("Local", "Local"),
                    ("Central", "Central"),
                    ("Devolved", "Devolved"),
                ],
                db_index=True,
                default="General foundation",
                max_length=50,
                null=True,
            ),
        ),
        migrations.RunPython(update_general_grantmaker, update_general_foundation),
        migrations.AlterField(
            model_name="funder",
            name="segment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Donor Advised Fund", "Donor Advised Fund"),
                    ("Wellcome Trust", "Wellcome Trust"),
                    ("Charity", "Charity"),
                    ("Lottery Distributor", "Lottery Distributor"),
                    ("Arms Length Body", "Arms Length Body"),
                    ("Corporate Foundation", "Corporate Foundation"),
                    ("Family Foundation", "Family Foundation"),
                    ("Fundraising Grantmaker", "Fundraising Grantmaker"),
                    ("General foundation", "General foundation"),
                    ("Member/Trade Funded", "Member/Trade Funded"),
                    ("NHS/Hospital Foundation", "NHS/Hospital Foundation"),
                    ("Government/Lottery Endowed", "Government/Lottery Endowed"),
                    ("Small grantmaker", "Small grantmaker"),
                    ("Community Foundation", "Community Foundation"),
                    ("Local", "Local"),
                    ("Central", "Central"),
                    ("Devolved", "Devolved"),
                ],
                db_index=True,
                default="General foundation",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="funderfinancialyear",
            name="segment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Donor Advised Fund", "Donor Advised Fund"),
                    ("Wellcome Trust", "Wellcome Trust"),
                    ("Charity", "Charity"),
                    ("Lottery Distributor", "Lottery Distributor"),
                    ("Arms Length Body", "Arms Length Body"),
                    ("Corporate Foundation", "Corporate Foundation"),
                    ("Family Foundation", "Family Foundation"),
                    ("Fundraising Grantmaker", "Fundraising Grantmaker"),
                    ("General foundation", "General foundation"),
                    ("Member/Trade Funded", "Member/Trade Funded"),
                    ("NHS/Hospital Foundation", "NHS/Hospital Foundation"),
                    ("Government/Lottery Endowed", "Government/Lottery Endowed"),
                    ("Small grantmaker", "Small grantmaker"),
                    ("Community Foundation", "Community Foundation"),
                    ("Local", "Local"),
                    ("Central", "Central"),
                    ("Devolved", "Devolved"),
                ],
                db_index=True,
                default="General foundation",
                max_length=50,
                null=True,
            ),
        ),
    ]
