# Generated by Django 5.0.6 on 2024-11-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ukgrantmaking", "0087_alter_funder_segment_alter_funder_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cleaningstatus",
            name="n",
            field=models.IntegerField(
                default=50,
                help_text="Number of records to return. Set to 0 to return all records.",
            ),
        ),
    ]
