# Generated by Django 5.0.6 on 2024-11-28 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ukgrantmaking", "0089_alter_cleaningstatusquery_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="funder",
            old_name="latest_year",
            new_name="current_year",
        ),
        migrations.AlterModelOptions(
            name="funder",
            options={"ordering": ["-current_year__scaling"]},
        ),
        migrations.AlterField(
            model_name="funder",
            name="current_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="funder_current_year",
                to="ukgrantmaking.funderfinancialyear",
            ),
        ),
    ]
