# Generated by Django 5.0.6 on 2024-11-28 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ukgrantmaking",
            "0090_alter_funder_options_remove_funder_latest_year_and_more",
        ),
    ]

    operations = [
        migrations.RunSQL("""
        ALTER INDEX IF EXISTS ukgrantmaking_funder_latest_year_id_b2fc82e6
        RENAME TO ukgrantmaking_funder_current_year_id_b2fc82e6
        """),
        migrations.AddField(
            model_name="funder",
            name="latest_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="funder_latest_year",
                to="ukgrantmaking.funderfinancialyear",
            ),
        ),
    ]
