# Generated by Django 5.0.6 on 2024-11-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ukgrantmaking", "0092_alter_funder_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="funder",
            name="category",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Case(
                    models.When(
                        segment="Community Foundation",
                        then=models.Value("Trusts and Foundations"),
                    ),
                    models.When(
                        segment="Corporate Foundation",
                        then=models.Value("Trusts and Foundations"),
                    ),
                    models.When(
                        segment="Family Foundation",
                        then=models.Value("Trusts and Foundations"),
                    ),
                    models.When(
                        segment="Fundraising Grantmaker",
                        then=models.Value("Trusts and Foundations"),
                    ),
                    models.When(
                        segment="General foundation",
                        then=models.Value("Trusts and Foundations"),
                    ),
                    models.When(
                        segment="Government/Lottery Endowed",
                        then=models.Value("Trusts and Foundations"),
                    ),
                    models.When(
                        segment="Member/Trade Funded",
                        then=models.Value("Trusts and Foundations"),
                    ),
                    models.When(
                        segment="Small grantmaker",
                        then=models.Value("Trusts and Foundations"),
                    ),
                    models.When(
                        segment="Wellcome Trust",
                        then=models.Value("Trusts and Foundations"),
                    ),
                    models.When(
                        segment="Lottery Distributor", then=models.Value("Lottery")
                    ),
                    models.When(segment="Charity", then=models.Value("Charity")),
                    models.When(
                        segment="NHS/Hospital Foundation", then=models.Value("Charity")
                    ),
                    models.When(segment="Local", then=models.Value("Government")),
                    models.When(segment="Central", then=models.Value("Government")),
                    models.When(segment="Devolved", then=models.Value("Government")),
                    models.When(
                        segment="Arms Length Body", then=models.Value("Government")
                    ),
                    models.When(
                        segment="Donor Advised Fund", then=models.Value("Other")
                    ),
                    output_field=models.CharField(max_length=255),
                ),
                output_field=models.CharField(max_length=255),
            ),
        ),
    ]
