# Generated by Django 5.0.6 on 2024-12-16 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ukgrantmaking", "0094_funderfinancialyear_category_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="funderyear",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="funderfinancialyear",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="funder_financial_years",
                to="ukgrantmaking.fundertag",
            ),
        ),
        migrations.AlterField(
            model_name="funderyear",
            name="original_funder_financial_year",
            field=models.ForeignKey(
                db_constraint=False,
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="new_funder_years",
                to="ukgrantmaking.funderfinancialyear",
            ),
        ),
        migrations.AddConstraint(
            model_name="funderyear",
            constraint=models.UniqueConstraint(
                fields=(
                    "funder_financial_year",
                    "financial_year_end",
                    "original_funder_financial_year",
                ),
                name="unique_funder_year",
            ),
        ),
    ]
