# Generated by Django 5.0.6 on 2024-12-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ukgrantmaking", "0097_auto_20241216_1944"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="funderyear",
            name="original_funder_financial_year",
        ),
        migrations.AddConstraint(
            model_name="funderyear",
            constraint=models.UniqueConstraint(
                fields=("funder_financial_year", "financial_year_end"),
                name="unique_funder_year",
            ),
        ),
    ]
