# Generated by Django 5.0.6 on 2025-01-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ukgrantmaking", "0098_auto_20241216_1945"),
    ]

    operations = [
        migrations.AddField(
            model_name="grant",
            name="lottery_grant_type",
            field=models.CharField(
                blank=True,
                choices=[("Exchequer", "Exchequer"), ("Lottery", "Lottery")],
                db_index=True,
                max_length=50,
                null=True,
            ),
        ),
    ]
