# Generated by Django 5.0.6 on 2025-01-16 17:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ukgrantmaking", "0099_grant_lottery_grant_type"),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE OR REPLACE VIEW ukgrantmaking_funders_view AS
            WITH spend_data AS (
                SELECT coalesce(new_funder_financial_year_id, funder_financial_year_id) AS funder_financial_year_id,
                    max(financial_year_end) AS financial_year_end,
                    sum(income) AS income,
                    sum(income_investment) AS income_investment,
                    sum(spending) AS spending,
                    sum(spending_investment) AS spending_investment,
                    sum(spending_charitable) AS spending_charitable,
                    sum(spending_grant_making) AS spending_grant_making,
                    sum(spending_grant_making_individuals) AS spending_grant_making_individuals,
                    sum(spending_grant_making_institutions) AS spending_grant_making_institutions
                FROM ukgrantmaking_funderyear
                GROUP BY 1
            ),
            balance_sheet AS (
                SELECT DISTINCT ON (coalesce(new_funder_financial_year_id, funder_financial_year_id))
                    coalesce(new_funder_financial_year_id, funder_financial_year_id) AS funder_financial_year_id,
                    financial_year_end,
                    total_net_assets,
                    funds,
                    funds_endowment,
                    funds_restricted,
                    funds_unrestricted,
                    employees
                FROM ukgrantmaking_funderyear
                ORDER BY coalesce(new_funder_financial_year_id, funder_financial_year_id),
                    financial_year_end DESC
            ),
            tags AS (
                SELECT funderfinancialyear_id, array_agg(t.tag) AS tags 
                FROM ukgrantmaking_funderfinancialyear_tags ffyt
                    INNER JOIN ukgrantmaking_fundertag t
                        ON ffyt.fundertag_id = t.slug 
                GROUP BY 1
            )
            SELECT f.org_id,
                f."name",
                ffy.segment,
                ffy.category,
                ffy.makes_grants_to_individuals,
                tags.tags,
                fy.fy,
                spend_data.financial_year_end,
                spend_data.income,
                spend_data.income_investment,
                spend_data.spending,
                spend_data.spending_investment,
                spend_data.spending_charitable,
                spend_data.spending_grant_making,
                spend_data.spending_grant_making_individuals,
                spend_data.spending_grant_making_institutions,
                balance_sheet.total_net_assets,
                balance_sheet.funds,
                balance_sheet.funds_endowment,
                balance_sheet.funds_restricted,
                balance_sheet.funds_unrestricted,
                balance_sheet.employees
            FROM ukgrantmaking_funderfinancialyear ffy 
                INNER JOIN ukgrantmaking_financialyear fy
                    ON ffy.financial_year_id = fy.fy 
                INNER JOIN ukgrantmaking_funder f
                    ON ffy.funder_id = f.org_id 
                LEFT OUTER JOIN tags
                    ON tags.funderfinancialyear_id = ffy.id
                LEFT OUTER JOIN spend_data
                    ON spend_data.funder_financial_year_id = ffy.id
                LEFT OUTER JOIN balance_sheet
                    ON balance_sheet.funder_financial_year_id = ffy.id
            WHERE fy."current" 
                AND ffy.included
            ORDER BY spending_grant_making DESC NULLS LAST
            """,
            "DROP VIEW ukgrantmaking_funders_view",
        )
    ]
