# Generated by Django 5.0.6 on 2025-01-17 15:55

from django.db import migrations, models

fields_to_replace = {
    "funder_financial_year__funder__org_id": "funder__org_id",
    "funder_financial_year__funder__name": "funder__name",
    "funder_financial_year__funder__status": "funder__status",
    "funder_financial_year__funder__date_of_registration": "funder__date_of_registration",
    "funder_financial_year__funder__date_of_removal": "funder__date_of_removal",
    "funder_financial_year__funder__active": "funder__active",
    "funder_financial_year__funder__latest_year__scaling": "funder__latest_year__scaling",
    "funder_financial_year__scaling": "scaling",
    "funder_financial_year__tags__tag": "tags__tag",
    "funder_financial_year__segment": "segment",
    "funder_financial_year__category": "category",
    "funder_financial_year__included": "included",
    "funder_financial_year__makes_grants_to_individuals": "makes_grants_to_individuals",
    "funder_financial_year__checked": "checked",
    "funder_financial_year__checked_on": "checked_on",
    "funder_financial_year__checked_by": "checked_by",
    "funder_financial_year__notes": "notes",
    "funder_financial_year__date_added": "date_added",
    "funder_financial_year__date_updated": "date_updated",
}


def replace_fields(apps, schema_editor):
    CleaningStatus = apps.get_model("ukgrantmaking", "CleaningStatus")
    CleaningStatusQuery = apps.get_model("ukgrantmaking", "CleaningStatusQuery")

    for row in CleaningStatus.objects.filter(sort_by__in=fields_to_replace.keys()):
        row.sort_by = fields_to_replace[row.sort_by]
        row.save()

    for row in CleaningStatusQuery.objects.filter(field__in=fields_to_replace.keys()):
        row.field = fields_to_replace[row.field]
        row.save()


def replace_fields_backwards(apps, schema_editor):
    fields_to_replace_reverse = {v: k for k, v in fields_to_replace.items()}
    CleaningStatus = apps.get_model("ukgrantmaking", "CleaningStatus")
    CleaningStatusQuery = apps.get_model("ukgrantmaking", "CleaningStatusQuery")

    for row in CleaningStatus.objects.filter(
        sort_by__in=fields_to_replace_reverse.keys()
    ):
        row.sort_by = fields_to_replace_reverse[row.field]
        row.save()

    for row in CleaningStatusQuery.objects.filter(
        field__in=fields_to_replace_reverse.keys()
    ):
        row.field = fields_to_replace_reverse[row.field]
        row.save()


class Migration(migrations.Migration):
    dependencies = [
        ("ukgrantmaking", "0100_auto_20250116_1755"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cleaningstatus",
            name="sort_by",
            field=models.CharField(
                choices=[
                    (
                        "Grantmaker",
                        [
                            ("financial_year_end", "Financial Year End"),
                            ("income", "Income"),
                            ("income_investment", "Income investment"),
                            ("spending", "Spending"),
                            ("spending_investment", "Spending investment"),
                            ("spending_charitable", "Spending charitable"),
                            ("spending_grant_making", "Spending grant making"),
                            (
                                "spending_grant_making_individuals",
                                "Spending grant making individuals",
                            ),
                            (
                                "spending_grant_making_institutions_charitable",
                                "Spending grant making institutions charitable",
                            ),
                            (
                                "spending_grant_making_institutions_noncharitable",
                                "Spending grant making institutions noncharitable",
                            ),
                            (
                                "spending_grant_making_institutions_unknown",
                                "Spending grant making institutions unknown",
                            ),
                            (
                                "spending_grant_making_institutions",
                                "Spending grant making institutions",
                            ),
                            ("total_net_assets", "Total net assets"),
                            ("funds", "Funds"),
                            ("funds_endowment", "Funds endowment"),
                            ("funds_restricted", "Funds restricted"),
                            ("funds_unrestricted", "Funds unrestricted"),
                            ("employees", "Employees"),
                            ("checked", "Checked"),
                            ("funder__org_id", "Funder ID"),
                            ("funder__name", "Funder Name"),
                            ("funder__status", "Funder status"),
                            ("funder__date_of_registration", "Registration date"),
                            ("funder__date_of_removal", "Removal date"),
                            ("funder__active", "Funder Active"),
                            (
                                "funder__latest_year__scaling",
                                "Grantmaker size (latest)",
                            ),
                            ("scaling", "Grantmaker size"),
                            ("tags__tag", "Tags"),
                            ("segment", "Segment"),
                            ("category", "Category"),
                            ("included", "Included"),
                            (
                                "makes_grants_to_individuals",
                                "Makes grants to individuals",
                            ),
                            ("checked_on", "Checked on"),
                            ("checked_by", "Checked by"),
                            ("notes", "Notes"),
                            ("date_added", "Date added"),
                            ("date_updated", "Date updated"),
                        ],
                    ),
                    (
                        "Grant",
                        [
                            ("title", "Title"),
                            ("description", "Description"),
                            ("currency", "Currency"),
                            ("amount_awarded", "Amount awarded"),
                            ("amount_awarded_GBP", "Amount awarded GBP"),
                            ("award_date", "Award date"),
                            ("planned_dates_duration", "Planned dates duration"),
                            ("planned_dates_startDate", "Planned dates startDate"),
                            ("planned_dates_endDate", "Planned dates endDate"),
                            ("recipient_organisation_id", "Recipient organisation id"),
                            (
                                "recipient_organisation_name",
                                "Recipient organisation name",
                            ),
                            ("recipient_individual_id", "Recipient individual id"),
                            ("recipient_individual_name", "Recipient individual name"),
                            (
                                "recipient_individual_primary_grant_reason",
                                "Recipient individual primary grant reason",
                            ),
                            (
                                "recipient_individual_secondary_grant_reason",
                                "Recipient individual secondary grant reason",
                            ),
                            (
                                "recipient_individual_grant_purpose",
                                "Recipient individual grant purpose",
                            ),
                            ("recipient_type", "Recipient type"),
                            ("funding_organisation_id", "Funding organisation id"),
                            ("funding_organisation_name", "Funding organisation name"),
                            ("funding_organisation_type", "Funding organisation type"),
                            ("regrant_type", "Regrant type"),
                            ("location_scope", "Location scope"),
                            ("grant_programme_title", "Grant programme title"),
                            ("publisher_prefix", "Publisher prefix"),
                            ("publisher_name", "Publisher name"),
                            ("license", "License"),
                            ("recipient_location_rgn", "Recipient location rgn"),
                            ("recipient_location_ctry", "Recipient location ctry"),
                            ("beneficiary_location_rgn", "Beneficiary location rgn"),
                            ("beneficiary_location_ctry", "Beneficiary location ctry"),
                            ("funder", "Funder"),
                            ("recipient", "Recipient"),
                            ("recipient_type_manual", "Recipient type manual"),
                            ("inclusion", "Inclusion"),
                            ("notes", "Notes"),
                            ("checked_by", "Checked by"),
                            ("annual_amount", "Annual amount"),
                        ],
                    ),
                ],
                default="funder_financial_year__funder__latest_year__scaling",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="cleaningstatusquery",
            name="field",
            field=models.CharField(
                choices=[
                    (
                        "Grantmaker",
                        [
                            ("financial_year_end", "Financial Year End"),
                            ("income", "Income"),
                            ("income_investment", "Income investment"),
                            ("spending", "Spending"),
                            ("spending_investment", "Spending investment"),
                            ("spending_charitable", "Spending charitable"),
                            ("spending_grant_making", "Spending grant making"),
                            (
                                "spending_grant_making_individuals",
                                "Spending grant making individuals",
                            ),
                            (
                                "spending_grant_making_institutions_charitable",
                                "Spending grant making institutions charitable",
                            ),
                            (
                                "spending_grant_making_institutions_noncharitable",
                                "Spending grant making institutions noncharitable",
                            ),
                            (
                                "spending_grant_making_institutions_unknown",
                                "Spending grant making institutions unknown",
                            ),
                            (
                                "spending_grant_making_institutions",
                                "Spending grant making institutions",
                            ),
                            ("total_net_assets", "Total net assets"),
                            ("funds", "Funds"),
                            ("funds_endowment", "Funds endowment"),
                            ("funds_restricted", "Funds restricted"),
                            ("funds_unrestricted", "Funds unrestricted"),
                            ("employees", "Employees"),
                            ("checked", "Checked"),
                            ("funder__org_id", "Funder ID"),
                            ("funder__name", "Funder Name"),
                            ("funder__status", "Funder status"),
                            ("funder__date_of_registration", "Registration date"),
                            ("funder__date_of_removal", "Removal date"),
                            ("funder__active", "Funder Active"),
                            (
                                "funder__latest_year__scaling",
                                "Grantmaker size (latest)",
                            ),
                            ("scaling", "Grantmaker size"),
                            ("tags__tag", "Tags"),
                            ("segment", "Segment"),
                            ("category", "Category"),
                            ("included", "Included"),
                            (
                                "makes_grants_to_individuals",
                                "Makes grants to individuals",
                            ),
                            ("checked_on", "Checked on"),
                            ("checked_by", "Checked by"),
                            ("notes", "Notes"),
                            ("date_added", "Date added"),
                            ("date_updated", "Date updated"),
                        ],
                    ),
                    (
                        "Grant",
                        [
                            ("title", "Title"),
                            ("description", "Description"),
                            ("currency", "Currency"),
                            ("amount_awarded", "Amount awarded"),
                            ("amount_awarded_GBP", "Amount awarded GBP"),
                            ("award_date", "Award date"),
                            ("planned_dates_duration", "Planned dates duration"),
                            ("planned_dates_startDate", "Planned dates startDate"),
                            ("planned_dates_endDate", "Planned dates endDate"),
                            ("recipient_organisation_id", "Recipient organisation id"),
                            (
                                "recipient_organisation_name",
                                "Recipient organisation name",
                            ),
                            ("recipient_individual_id", "Recipient individual id"),
                            ("recipient_individual_name", "Recipient individual name"),
                            (
                                "recipient_individual_primary_grant_reason",
                                "Recipient individual primary grant reason",
                            ),
                            (
                                "recipient_individual_secondary_grant_reason",
                                "Recipient individual secondary grant reason",
                            ),
                            (
                                "recipient_individual_grant_purpose",
                                "Recipient individual grant purpose",
                            ),
                            ("recipient_type", "Recipient type"),
                            ("funding_organisation_id", "Funding organisation id"),
                            ("funding_organisation_name", "Funding organisation name"),
                            ("funding_organisation_type", "Funding organisation type"),
                            ("regrant_type", "Regrant type"),
                            ("location_scope", "Location scope"),
                            ("grant_programme_title", "Grant programme title"),
                            ("publisher_prefix", "Publisher prefix"),
                            ("publisher_name", "Publisher name"),
                            ("license", "License"),
                            ("recipient_location_rgn", "Recipient location rgn"),
                            ("recipient_location_ctry", "Recipient location ctry"),
                            ("beneficiary_location_rgn", "Beneficiary location rgn"),
                            ("beneficiary_location_ctry", "Beneficiary location ctry"),
                            ("funder", "Funder"),
                            ("recipient", "Recipient"),
                            ("recipient_type_manual", "Recipient type manual"),
                            ("inclusion", "Inclusion"),
                            ("notes", "Notes"),
                            ("checked_by", "Checked by"),
                            ("annual_amount", "Annual amount"),
                        ],
                    ),
                ],
                max_length=255,
            ),
        ),
        migrations.RunPython(replace_fields, replace_fields_backwards),
    ]
