# Generated by Django 5.0.6 on 2025-01-17 16:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("ukgrantmaking", "0103_remove_funderfinancialyear_notes_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="funderfinancialyear",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="fundernote",
            name="funder",
        ),
        migrations.RemoveField(
            model_name="funderyear",
            name="checked",
        ),
        migrations.RemoveField(
            model_name="funderyear",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="grant",
            name="notes",
        ),
        migrations.AddIndex(
            model_name="fundernote",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="ukgrantmaki_content_ff0f8b_idx",
            ),
        ),
    ]
