# Generated by Django 5.0.6 on 2025-04-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ukgrantmaking", "0119_grant_funding_organisation_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grant",
            name="regrant_type_manual",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FRG010", "Common Regrant"),
                    ("FRG020", "Transfer to intermediary"),
                    ("FRG030", "Match funding"),
                    ("FRG040", "Funder collaboration"),
                    ("FRG050", "Fiscal sponsor"),
                    ("FRG060", "Endowment"),
                    ("FRG070", "Multipurpose"),
                    ("NOT_REGRANT", "Not regrant"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="regrant_type_registered",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FRG010", "Common Regrant"),
                    ("FRG020", "Transfer to intermediary"),
                    ("FRG030", "Match funding"),
                    ("FRG040", "Funder collaboration"),
                    ("FRG050", "Fiscal sponsor"),
                    ("FRG060", "Endowment"),
                    ("FRG070", "Multipurpose"),
                    ("NOT_REGRANT", "Not regrant"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
