# Generated by Django 5.0.6 on 2025-10-20 09:11

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ukgrantmaking", "0120_alter_grant_regrant_type_manual_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="funder",
            name="ctry_aoo",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="funder",
            name="ctry_hq",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="funder",
            name="how",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="funder",
            name="london_aoo",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="funder",
            name="london_hq",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="funder",
            name="rgn_aoo",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="funder",
            name="rgn_hq",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="funder",
            name="scale_manual",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Local", "Local"),
                    ("National", "National"),
                    ("Overseas", "Overseas"),
                    ("National and Overseas", "National and Overseas"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="funder",
            name="scale_registered",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Local", "Local"),
                    ("National", "National"),
                    ("Overseas", "Overseas"),
                    ("National and Overseas", "National and Overseas"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="funder",
            name="what",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="funder",
            name="who",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="funder",
            name="scale",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Coalesce(
                    "scale_manual", "scale_registered"
                ),
                output_field=models.CharField(
                    blank=True,
                    choices=[
                        ("Local", "Local"),
                        ("National", "National"),
                        ("Overseas", "Overseas"),
                        ("National and Overseas", "National and Overseas"),
                    ],
                    max_length=50,
                    null=True,
                ),
            ),
        ),
    ]
