# Generated by Django 5.0.6 on 2025-10-21 14:42

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ukgrantmaking", "0121_funder_ctry_aoo_funder_ctry_hq_funder_how_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funder",
            name="scale",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Coalesce(
                    "scale_manual", "scale_registered"
                ),
                output_field=models.CharField(
                    blank=True,
                    choices=[
                        ("Local", "Local"),
                        ("Regional", "Regional"),
                        ("National", "National"),
                        ("Overseas", "Overseas"),
                        ("National and Overseas", "National and Overseas"),
                    ],
                    max_length=50,
                    null=True,
                ),
            ),
        ),
        migrations.AlterField(
            model_name="funder",
            name="scale_manual",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Local", "Local"),
                    ("Regional", "Regional"),
                    ("National", "National"),
                    ("Overseas", "Overseas"),
                    ("National and Overseas", "National and Overseas"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="funder",
            name="scale_registered",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Local", "Local"),
                    ("Regional", "Regional"),
                    ("National", "National"),
                    ("Overseas", "Overseas"),
                    ("National and Overseas", "National and Overseas"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="grantrecipient",
            name="scale",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Coalesce(
                    "scale_manual", "scale_registered"
                ),
                output_field=models.CharField(
                    blank=True,
                    choices=[
                        ("Local", "Local"),
                        ("Regional", "Regional"),
                        ("National", "National"),
                        ("Overseas", "Overseas"),
                        ("National and Overseas", "National and Overseas"),
                    ],
                    max_length=50,
                    null=True,
                ),
            ),
        ),
        migrations.AlterField(
            model_name="grantrecipient",
            name="scale_manual",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Local", "Local"),
                    ("Regional", "Regional"),
                    ("National", "National"),
                    ("Overseas", "Overseas"),
                    ("National and Overseas", "National and Overseas"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="grantrecipient",
            name="scale_registered",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Local", "Local"),
                    ("Regional", "Regional"),
                    ("National", "National"),
                    ("Overseas", "Overseas"),
                    ("National and Overseas", "National and Overseas"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
