# Generated by Django 5.0.6 on 2025-10-23 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ukgrantmaking", "0122_alter_funder_scale_alter_funder_scale_manual_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="funder",
            name="ctry_aoo_name",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="funder",
            name="ctry_hq_name",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="funder",
            name="la_aoo",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="funder",
            name="la_aoo_name",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="funder",
            name="la_hq",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="funder",
            name="la_hq_name",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="funder",
            name="postcode",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="funder",
            name="rgn_aoo_name",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="funder",
            name="rgn_hq_name",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="grantrecipient",
            name="ctry_aoo_name",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="grantrecipient",
            name="ctry_hq_name",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="grantrecipient",
            name="la_aoo",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="grantrecipient",
            name="la_aoo_name",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="grantrecipient",
            name="la_hq",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="grantrecipient",
            name="la_hq_name",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="grantrecipient",
            name="postcode",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="grantrecipient",
            name="rgn_aoo_name",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="grantrecipient",
            name="rgn_hq_name",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="funder",
            name="category",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Case(
                    models.When(
                        segment="Community Foundation",
                        then=models.Value("Trusts and Foundations"),
                    ),
                    models.When(
                        segment="Corporate Foundation",
                        then=models.Value("Trusts and Foundations"),
                    ),
                    models.When(
                        segment="Family Foundation",
                        then=models.Value("Trusts and Foundations"),
                    ),
                    models.When(
                        segment="Fundraising Grantmaker",
                        then=models.Value("Trusts and Foundations"),
                    ),
                    models.When(
                        segment="General Foundation",
                        then=models.Value("Trusts and Foundations"),
                    ),
                    models.When(
                        segment="Government/Lottery Endowed",
                        then=models.Value("Trusts and Foundations"),
                    ),
                    models.When(
                        segment="Member/Trade Funded",
                        then=models.Value("Trusts and Foundations"),
                    ),
                    models.When(
                        segment="Small Grantmaker",
                        then=models.Value("Trusts and Foundations"),
                    ),
                    models.When(
                        segment="Wellcome Trust",
                        then=models.Value("Trusts and Foundations"),
                    ),
                    models.When(
                        segment="National Lottery Distributor",
                        then=models.Value("National Lottery"),
                    ),
                    models.When(segment="Charity", then=models.Value("Charity")),
                    models.When(
                        segment="NHS/Hospital Foundation", then=models.Value("Charity")
                    ),
                    models.When(segment="Local", then=models.Value("Government")),
                    models.When(segment="Central", then=models.Value("Government")),
                    models.When(segment="Devolved", then=models.Value("Government")),
                    models.When(
                        segment="Arms Length Body", then=models.Value("Government")
                    ),
                    models.When(
                        segment="Donor Advised Fund", then=models.Value("Other")
                    ),
                    output_field=models.CharField(max_length=255),
                ),
                output_field=models.CharField(max_length=255),
                verbose_name="Funder category (derived from segment)",
            ),
        ),
        migrations.AlterField(
            model_name="funder",
            name="charity_number",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Charity Number"
            ),
        ),
        migrations.AlterField(
            model_name="funder",
            name="how",
            field=models.JSONField(
                blank=True, null=True, verbose_name="How the charity operates"
            ),
        ),
        migrations.AlterField(
            model_name="funder",
            name="included",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="Included as a funder"
            ),
        ),
        migrations.AlterField(
            model_name="funder",
            name="makes_grants_to_individuals",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Makes grants to individuals"
            ),
        ),
        migrations.AlterField(
            model_name="funder",
            name="name_manual",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Name (manual override)",
            ),
        ),
        migrations.AlterField(
            model_name="funder",
            name="name_registered",
            field=models.CharField(
                max_length=255, verbose_name="Name (from regulator)"
            ),
        ),
        migrations.AlterField(
            model_name="funder",
            name="org_id",
            field=models.CharField(
                max_length=255,
                primary_key=True,
                serialize=False,
                verbose_name="Organisation Identifier",
            ),
        ),
        migrations.AlterField(
            model_name="funder",
            name="segment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Donor Advised Fund", "Donor Advised Fund"),
                    ("Wellcome Trust", "Wellcome Trust"),
                    ("Charity", "Charity"),
                    ("National Lottery Distributor", "National Lottery Distributor"),
                    ("Arms Length Body", "Arms Length Body"),
                    ("Corporate Foundation", "Corporate Foundation"),
                    ("Family Foundation", "Family Foundation"),
                    ("Fundraising Grantmaker", "Fundraising Grantmaker"),
                    ("General Foundation", "General Foundation"),
                    ("Member/Trade Funded", "Member/Trade Funded"),
                    ("NHS/Hospital Foundation", "NHS/Hospital Foundation"),
                    ("Government/Lottery Endowed", "Government/Lottery Endowed"),
                    ("Small Grantmaker", "Small Grantmaker"),
                    ("Community Foundation", "Community Foundation"),
                    ("Local", "Local"),
                    ("Central", "Central"),
                    ("Devolved", "Devolved"),
                ],
                db_index=True,
                default="General Foundation",
                max_length=50,
                null=True,
                verbose_name="Funder segment",
            ),
        ),
        migrations.AlterField(
            model_name="funder",
            name="status",
            field=models.CharField(
                choices=[
                    ("Unchecked", "Unchecked"),
                    ("Checked", "Checked"),
                    ("New", "New"),
                    ("For Review", "For Review"),
                ],
                db_index=True,
                default="Unchecked",
                max_length=50,
                verbose_name="Record status",
            ),
        ),
        migrations.AlterField(
            model_name="funder",
            name="successor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="predecessors",
                to="ukgrantmaking.funder",
                verbose_name="Organisation Identifier of successor organisation",
            ),
        ),
        migrations.AlterField(
            model_name="funder",
            name="what",
            field=models.JSONField(
                blank=True, null=True, verbose_name="What the charity does"
            ),
        ),
        migrations.AlterField(
            model_name="funder",
            name="who",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Who the charity helps"
            ),
        ),
        migrations.AlterField(
            model_name="grantrecipient",
            name="how",
            field=models.JSONField(
                blank=True, null=True, verbose_name="How the charity operates"
            ),
        ),
        migrations.AlterField(
            model_name="grantrecipient",
            name="what",
            field=models.JSONField(
                blank=True, null=True, verbose_name="What the charity does"
            ),
        ),
        migrations.AlterField(
            model_name="grantrecipient",
            name="who",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Who the charity helps"
            ),
        ),
    ]
