# Generated by Django 5.0.6 on 2025-11-20 10:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ukgrantmaking", "0123_funder_ctry_aoo_name_funder_ctry_hq_name_and_more"),
    ]

    operations = [
        migrations.RunSQL("DROP VIEW ukgrantmaking_funders_view"),
    ]
