# Generated by Django 5.2.8 on 2025-11-20 12:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ukgrantmaking', '0125_auto_20251120_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundersView',
            fields=[
                ('org_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('segment', models.CharField(blank=True, choices=[('Donor Advised Fund', 'Donor Advised Fund'), ('Wellcome Trust', 'Wellcome Trust'), ('Charity', 'Charity'), ('National Lottery Distributor', 'National Lottery Distributor'), ('Arms Length Body', 'Arms Length Body'), ('Corporate Foundation', 'Corporate Foundation'), ('Family Foundation', 'Family Foundation'), ('Fundraising Grantmaker', 'Fundraising Grantmaker'), ('General Foundation', 'General Foundation'), ('Member/Trade Funded', 'Member/Trade Funded'), ('NHS/Hospital Foundation', 'NHS/Hospital Foundation'), ('Government/Lottery Endowed', 'Government/Lottery Endowed'), ('Small Grantmaker', 'Small Grantmaker'), ('Community Foundation', 'Community Foundation'), ('Local', 'Local'), ('Central', 'Central'), ('Devolved', 'Devolved')], db_index=True, default='General Foundation', max_length=50, null=True, verbose_name='Funder segment')),
                ('category', models.CharField(blank=True, choices=[('Trusts and Foundations', 'Trusts and Foundations'), ('National Lottery', 'National Lottery'), ('Charity', 'Charity'), ('Government', 'Government'), ('Other', 'Other')], db_index=True, default='Trusts and Foundations', max_length=50, null=True, verbose_name='Funder category')),
                ('makes_grants_to_individuals', models.BooleanField(null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None)),
                ('fy', models.CharField(max_length=9)),
                ('financial_year_end', models.DateField(null=True)),
                ('income', models.BigIntegerField(null=True)),
                ('income_investment', models.BigIntegerField(null=True)),
                ('spending', models.BigIntegerField(null=True)),
                ('spending_investment', models.BigIntegerField(null=True)),
                ('spending_charitable', models.BigIntegerField(null=True)),
                ('spending_grant_making', models.BigIntegerField(null=True)),
                ('spending_grant_making_individuals', models.BigIntegerField(null=True)),
                ('spending_grant_making_institutions', models.BigIntegerField(null=True)),
                ('total_net_assets', models.BigIntegerField(null=True)),
                ('funds', models.BigIntegerField(null=True)),
                ('funds_endowment', models.BigIntegerField(null=True)),
                ('funds_restricted', models.BigIntegerField(null=True)),
                ('funds_unrestricted', models.BigIntegerField(null=True)),
                ('employees', models.IntegerField(null=True)),
                ('employees_permanent', models.IntegerField(null=True)),
                ('employees_fixedterm', models.IntegerField(null=True)),
                ('employees_selfemployed', models.IntegerField(null=True)),
                ('checked', models.TextField(null=True)),
                ('checked_by_id', models.IntegerField(null=True)),
                ('checked_on', models.DateTimeField(null=True)),
                ('tags_list', models.TextField(null=True)),
                ('tags_json', models.TextField(null=True)),
                ('tags_json_text', models.TextField(null=True)),
                ('segment_year', models.CharField(blank=True, choices=[('Donor Advised Fund', 'Donor Advised Fund'), ('Wellcome Trust', 'Wellcome Trust'), ('Charity', 'Charity'), ('National Lottery Distributor', 'National Lottery Distributor'), ('Arms Length Body', 'Arms Length Body'), ('Corporate Foundation', 'Corporate Foundation'), ('Family Foundation', 'Family Foundation'), ('Fundraising Grantmaker', 'Fundraising Grantmaker'), ('General Foundation', 'General Foundation'), ('Member/Trade Funded', 'Member/Trade Funded'), ('NHS/Hospital Foundation', 'NHS/Hospital Foundation'), ('Government/Lottery Endowed', 'Government/Lottery Endowed'), ('Small Grantmaker', 'Small Grantmaker'), ('Community Foundation', 'Community Foundation'), ('Local', 'Local'), ('Central', 'Central'), ('Devolved', 'Devolved')], db_index=True, default='General Foundation', max_length=50, null=True, verbose_name='Funder segment (in year)')),
                ('category_year', models.CharField(blank=True, choices=[('Trusts and Foundations', 'Trusts and Foundations'), ('National Lottery', 'National Lottery'), ('Charity', 'Charity'), ('Government', 'Government'), ('Other', 'Other')], db_index=True, default='Trusts and Foundations', max_length=50, null=True, verbose_name='Funder category (in year)')),
                ('makes_grants_to_individuals_year', models.BooleanField(null=True)),
                ('tags_list_year', models.TextField(null=True)),
                ('included_year', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'ukgrantmaking_funders_view',
                'managed': False,
            },
        ),
    ]
