# Generated by Django 5.2.8 on 2025-11-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ukgrantmaking", "0127_auto_20251125_1623"),
    ]

    operations = [
        migrations.CreateModel(
            name="FundersAnalysisView",
            fields=[
                (
                    "org_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("segment", models.CharField(max_length=50, verbose_name="Segment")),
                ("category", models.CharField(max_length=50, verbose_name="Category")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "html_name",
                    models.TextField(db_column="HTML_name", verbose_name="HTML Name"),
                ),
                (
                    "year1_fy",
                    models.CharField(
                        db_column="year1_fy",
                        max_length=10,
                        null=True,
                        verbose_name="Year 1 Financial Year",
                    ),
                ),
                (
                    "year1_financial_year_end",
                    models.DateField(
                        db_column="year1_financial_year_end",
                        null=True,
                        verbose_name="Year 1 End Date",
                    ),
                ),
                (
                    "year1_grantmaking_m",
                    models.DecimalField(
                        db_column="year1_Grantmaking_GBP_m",
                        decimal_places=3,
                        max_digits=18,
                        null=True,
                        verbose_name="Year 1 Grantmaking_GBP_m",
                    ),
                ),
                (
                    "year1_grantmaking_rank",
                    models.IntegerField(
                        db_column="year1_Grantmaking_Rank",
                        null=True,
                        verbose_name="Year 1 Grantmaking Rank",
                    ),
                ),
                (
                    "year1_grantmaking_band",
                    models.CharField(
                        db_column="year1_Grantmaking_Band",
                        max_length=50,
                        null=True,
                        verbose_name="Year 1 Grantmaking Band",
                    ),
                ),
                (
                    "year1_grantmaking_individuals_m",
                    models.DecimalField(
                        db_column="year1_Grantmaking_Individuals_GBP_m",
                        decimal_places=3,
                        max_digits=18,
                        null=True,
                        verbose_name="Year 1 Individuals Grantmaking_GBP_m",
                    ),
                ),
                (
                    "year1_grantmaking_individuals_rank",
                    models.IntegerField(
                        db_column="year1_Grantmaking_Individuals_Rank",
                        null=True,
                        verbose_name="Year 1 Individuals Grantmaking Rank",
                    ),
                ),
                (
                    "year1_income_m",
                    models.DecimalField(
                        db_column="year1_Income_GBP_m",
                        decimal_places=3,
                        max_digits=18,
                        null=True,
                        verbose_name="Year 1 Income_GBP_m",
                    ),
                ),
                (
                    "year1_spending_m",
                    models.DecimalField(
                        db_column="year1_Spending_GBP_m",
                        decimal_places=3,
                        max_digits=18,
                        null=True,
                        verbose_name="Year 1 Spending_GBP_m",
                    ),
                ),
                (
                    "year1_net_assets_m",
                    models.DecimalField(
                        db_column="year1_Net_Assets_GBP_m",
                        decimal_places=3,
                        max_digits=18,
                        null=True,
                        verbose_name="Year 1 Net Assets_GBP_m",
                    ),
                ),
                (
                    "year1_employees",
                    models.IntegerField(
                        db_column="year1_Employees",
                        null=True,
                        verbose_name="Year 1 Employees",
                    ),
                ),
                (
                    "year2_fy",
                    models.CharField(
                        db_column="year2_fy",
                        max_length=10,
                        null=True,
                        verbose_name="Year 2 Financial Year",
                    ),
                ),
                (
                    "year2_financial_year_end",
                    models.DateField(
                        db_column="year2_financial_year_end",
                        null=True,
                        verbose_name="Year 2 End Date",
                    ),
                ),
                (
                    "year2_grantmaking_m",
                    models.DecimalField(
                        db_column="year2_Grantmaking_GBP_m",
                        decimal_places=3,
                        max_digits=18,
                        null=True,
                        verbose_name="Year 2 Grantmaking_GBP_m",
                    ),
                ),
                (
                    "year2_grantmaking_rank",
                    models.IntegerField(
                        db_column="year2_Grantmaking_Rank",
                        null=True,
                        verbose_name="Year 2 Grantmaking Rank",
                    ),
                ),
                (
                    "year2_grantmaking_band",
                    models.CharField(
                        db_column="year2_Grantmaking_Band",
                        max_length=50,
                        null=True,
                        verbose_name="Year 2 Grantmaking Band",
                    ),
                ),
                (
                    "year2_grantmaking_individuals_m",
                    models.DecimalField(
                        db_column="year2_Grantmaking_Individuals_GBP_m",
                        decimal_places=3,
                        max_digits=18,
                        null=True,
                        verbose_name="Year 2 Individuals Grantmaking_GBP_m",
                    ),
                ),
                (
                    "year2_grantmaking_individuals_rank",
                    models.IntegerField(
                        db_column="year2_Grantmaking_Individuals_Rank",
                        null=True,
                        verbose_name="Year 2 Individuals Grantmaking Rank",
                    ),
                ),
                (
                    "year2_income_m",
                    models.DecimalField(
                        db_column="year2_Income_GBP_m",
                        decimal_places=3,
                        max_digits=18,
                        null=True,
                        verbose_name="Year 2 Income_GBP_m",
                    ),
                ),
                (
                    "year2_spending_m",
                    models.DecimalField(
                        db_column="year2_Spending_GBP_m",
                        decimal_places=3,
                        max_digits=18,
                        null=True,
                        verbose_name="Year 2 Spending_GBP_m",
                    ),
                ),
                (
                    "year2_net_assets_m",
                    models.DecimalField(
                        db_column="year2_Net_Assets_GBP_m",
                        decimal_places=3,
                        max_digits=18,
                        null=True,
                        verbose_name="Year 2 Net Assets_GBP_m",
                    ),
                ),
                (
                    "year2_employees",
                    models.IntegerField(
                        db_column="year2_Employees",
                        null=True,
                        verbose_name="Year 2 Employees",
                    ),
                ),
                (
                    "year3_fy",
                    models.CharField(
                        db_column="year3_fy",
                        max_length=10,
                        null=True,
                        verbose_name="Year 3 Financial Year",
                    ),
                ),
                (
                    "year3_financial_year_end",
                    models.DateField(
                        db_column="year3_financial_year_end",
                        null=True,
                        verbose_name="Year 3 End Date",
                    ),
                ),
                (
                    "year3_grantmaking_m",
                    models.DecimalField(
                        db_column="year3_Grantmaking_GBP_m",
                        decimal_places=3,
                        max_digits=18,
                        null=True,
                        verbose_name="Year 3 Grantmaking_GBP_m",
                    ),
                ),
                (
                    "year3_grantmaking_rank",
                    models.IntegerField(
                        db_column="year3_Grantmaking_Rank",
                        null=True,
                        verbose_name="Year 3 Grantmaking Rank",
                    ),
                ),
                (
                    "year3_grantmaking_band",
                    models.CharField(
                        db_column="year3_Grantmaking_Band",
                        max_length=50,
                        null=True,
                        verbose_name="Year 3 Grantmaking Band",
                    ),
                ),
                (
                    "year3_grantmaking_individuals_m",
                    models.DecimalField(
                        db_column="year3_Grantmaking_Individuals_GBP_m",
                        decimal_places=3,
                        max_digits=18,
                        null=True,
                        verbose_name="Year 3 Individuals Grantmaking_GBP_m",
                    ),
                ),
                (
                    "year3_grantmaking_individuals_rank",
                    models.IntegerField(
                        db_column="year3_Grantmaking_Individuals_Rank",
                        null=True,
                        verbose_name="Year 3 Individuals Grantmaking Rank",
                    ),
                ),
                (
                    "year3_income_m",
                    models.DecimalField(
                        db_column="year3_Income_GBP_m",
                        decimal_places=3,
                        max_digits=18,
                        null=True,
                        verbose_name="Year 3 Income_GBP_m",
                    ),
                ),
                (
                    "year3_spending_m",
                    models.DecimalField(
                        db_column="year3_Spending_GBP_m",
                        decimal_places=3,
                        max_digits=18,
                        null=True,
                        verbose_name="Year 3 Spending_GBP_m",
                    ),
                ),
                (
                    "year3_net_assets_m",
                    models.DecimalField(
                        db_column="year3_Net_Assets_GBP_m",
                        decimal_places=3,
                        max_digits=18,
                        null=True,
                        verbose_name="Year 3 Net Assets_GBP_m",
                    ),
                ),
                (
                    "year3_employees",
                    models.IntegerField(
                        db_column="year3_Employees",
                        null=True,
                        verbose_name="Year 3 Employees",
                    ),
                ),
                (
                    "year4_fy",
                    models.CharField(
                        db_column="year4_fy",
                        max_length=10,
                        null=True,
                        verbose_name="Year 4 Financial Year",
                    ),
                ),
                (
                    "year4_financial_year_end",
                    models.DateField(
                        db_column="year4_financial_year_end",
                        null=True,
                        verbose_name="Year 4 End Date",
                    ),
                ),
                (
                    "year4_grantmaking_m",
                    models.DecimalField(
                        db_column="year4_Grantmaking_GBP_m",
                        decimal_places=3,
                        max_digits=18,
                        null=True,
                        verbose_name="Year 4 Grantmaking_GBP_m",
                    ),
                ),
                (
                    "year4_grantmaking_rank",
                    models.IntegerField(
                        db_column="year4_Grantmaking_Rank",
                        null=True,
                        verbose_name="Year 4 Grantmaking Rank",
                    ),
                ),
                (
                    "year4_grantmaking_band",
                    models.CharField(
                        db_column="year4_Grantmaking_Band",
                        max_length=50,
                        null=True,
                        verbose_name="Year 4 Grantmaking Band",
                    ),
                ),
                (
                    "year4_grantmaking_individuals_m",
                    models.DecimalField(
                        db_column="year4_Grantmaking_Individuals_GBP_m",
                        decimal_places=3,
                        max_digits=18,
                        null=True,
                        verbose_name="Year 4 Individuals Grantmaking_GBP_m",
                    ),
                ),
                (
                    "year4_grantmaking_individuals_rank",
                    models.IntegerField(
                        db_column="year4_Grantmaking_Individuals_Rank",
                        null=True,
                        verbose_name="Year 4 Individuals Grantmaking Rank",
                    ),
                ),
                (
                    "year4_income_m",
                    models.DecimalField(
                        db_column="year4_Income_GBP_m",
                        decimal_places=3,
                        max_digits=18,
                        null=True,
                        verbose_name="Year 4 Income_GBP_m",
                    ),
                ),
                (
                    "year4_spending_m",
                    models.DecimalField(
                        db_column="year4_Spending_GBP_m",
                        decimal_places=3,
                        max_digits=18,
                        null=True,
                        verbose_name="Year 4 Spending_GBP_m",
                    ),
                ),
                (
                    "year4_net_assets_m",
                    models.DecimalField(
                        db_column="year4_Net_Assets_GBP_m",
                        decimal_places=3,
                        max_digits=18,
                        null=True,
                        verbose_name="Year 4 Net Assets_GBP_m",
                    ),
                ),
                (
                    "year4_employees",
                    models.IntegerField(
                        db_column="year4_Employees",
                        null=True,
                        verbose_name="Year 4 Employees",
                    ),
                ),
                (
                    "year5_fy",
                    models.CharField(
                        db_column="year5_fy",
                        max_length=10,
                        null=True,
                        verbose_name="Year 5 Financial Year",
                    ),
                ),
                (
                    "year5_financial_year_end",
                    models.DateField(
                        db_column="year5_financial_year_end",
                        null=True,
                        verbose_name="Year 5 End Date",
                    ),
                ),
                (
                    "year5_grantmaking_m",
                    models.DecimalField(
                        db_column="year5_Grantmaking_GBP_m",
                        decimal_places=3,
                        max_digits=18,
                        null=True,
                        verbose_name="Year 5 Grantmaking_GBP_m",
                    ),
                ),
                (
                    "year5_grantmaking_rank",
                    models.IntegerField(
                        db_column="year5_Grantmaking_Rank",
                        null=True,
                        verbose_name="Year 5 Grantmaking Rank",
                    ),
                ),
                (
                    "year5_grantmaking_band",
                    models.CharField(
                        db_column="year5_Grantmaking_Band",
                        max_length=50,
                        null=True,
                        verbose_name="Year 5 Grantmaking Band",
                    ),
                ),
                (
                    "year5_grantmaking_individuals_m",
                    models.DecimalField(
                        db_column="year5_Grantmaking_Individuals_GBP_m",
                        decimal_places=3,
                        max_digits=18,
                        null=True,
                        verbose_name="Year 5 Individuals Grantmaking_GBP_m",
                    ),
                ),
                (
                    "year5_grantmaking_individuals_rank",
                    models.IntegerField(
                        db_column="year5_Grantmaking_Individuals_Rank",
                        null=True,
                        verbose_name="Year 5 Individuals Grantmaking Rank",
                    ),
                ),
                (
                    "year5_income_m",
                    models.DecimalField(
                        db_column="year5_Income_GBP_m",
                        decimal_places=3,
                        max_digits=18,
                        null=True,
                        verbose_name="Year 5 Income_GBP_m",
                    ),
                ),
                (
                    "year5_spending_m",
                    models.DecimalField(
                        db_column="year5_Spending_GBP_m",
                        decimal_places=3,
                        max_digits=18,
                        null=True,
                        verbose_name="Year 5 Spending_GBP_m",
                    ),
                ),
                (
                    "year5_net_assets_m",
                    models.DecimalField(
                        db_column="year5_Net_Assets_GBP_m",
                        decimal_places=3,
                        max_digits=18,
                        null=True,
                        verbose_name="Year 5 Net Assets_GBP_m",
                    ),
                ),
                (
                    "year5_employees",
                    models.IntegerField(
                        db_column="year5_Employees",
                        null=True,
                        verbose_name="Year 5 Employees",
                    ),
                ),
                (
                    "charity_number",
                    models.CharField(
                        max_length=20, null=True, verbose_name="Charity Number"
                    ),
                ),
                (
                    "active",
                    models.CharField(
                        max_length=10, null=True, verbose_name="Active Status"
                    ),
                ),
                (
                    "date_of_registration",
                    models.DateField(null=True, verbose_name="Date of Registration"),
                ),
                (
                    "how",
                    models.CharField(
                        max_length=255, null=True, verbose_name="How Grants Are Made"
                    ),
                ),
                (
                    "what",
                    models.CharField(
                        max_length=255, null=True, verbose_name="What Grants Cover"
                    ),
                ),
                (
                    "who",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Who Grants Target"
                    ),
                ),
                (
                    "scale",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Funder Scale"
                    ),
                ),
                (
                    "la_hq",
                    models.CharField(
                        max_length=50, null=True, verbose_name="HQ Local Authority Code"
                    ),
                ),
                (
                    "la_hq_name",
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name="HQ Local Authority Name",
                    ),
                ),
                (
                    "rgn_hq",
                    models.CharField(
                        max_length=50, null=True, verbose_name="HQ Region Code"
                    ),
                ),
                (
                    "rgn_hq_name",
                    models.CharField(
                        max_length=255, null=True, verbose_name="HQ Region Name"
                    ),
                ),
                (
                    "ctry_hq",
                    models.CharField(
                        max_length=50, null=True, verbose_name="HQ Country Code"
                    ),
                ),
                (
                    "ctry_hq_name",
                    models.CharField(
                        max_length=255, null=True, verbose_name="HQ Country Name"
                    ),
                ),
                (
                    "la_aoo",
                    models.CharField(
                        max_length=50,
                        null=True,
                        verbose_name="AOO Local Authority Code",
                    ),
                ),
                (
                    "la_aoo_name",
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name="AOO Local Authority Name",
                    ),
                ),
                (
                    "rgn_aoo",
                    models.CharField(
                        max_length=50, null=True, verbose_name="AOO Region Code"
                    ),
                ),
                (
                    "rgn_aoo_name",
                    models.CharField(
                        max_length=255, null=True, verbose_name="AOO Region Name"
                    ),
                ),
                (
                    "ctry_aoo",
                    models.CharField(
                        max_length=50, null=True, verbose_name="AOO Country Code"
                    ),
                ),
                (
                    "ctry_aoo_name",
                    models.CharField(
                        max_length=255, null=True, verbose_name="AOO Country Name"
                    ),
                ),
                (
                    "london_aoo",
                    models.BooleanField(
                        db_column="london_aoo",
                        verbose_name="Area of Operation is London",
                    ),
                ),
                (
                    "london_hq",
                    models.BooleanField(
                        db_column="london_hq", verbose_name="Headquarters in London"
                    ),
                ),
                (
                    "has_2yrs_grantmaking",
                    models.BooleanField(
                        db_column="has_2yrs_Grantmaking",
                        verbose_name="Has 2 Yrs Grantmaking Data",
                    ),
                ),
                (
                    "has_2yrs_grantmaking_individuals",
                    models.BooleanField(
                        db_column="has_2yrs_Grantmaking_Individuals",
                        verbose_name="Has 2 Yrs Individuals Grantmaking Data",
                    ),
                ),
                (
                    "has_2yrs_income",
                    models.BooleanField(
                        db_column="has_2yrs_Income",
                        verbose_name="Has 2 Yrs Income Data",
                    ),
                ),
                (
                    "has_2yrs_spending",
                    models.BooleanField(
                        db_column="has_2yrs_Spending",
                        verbose_name="Has 2 Yrs Spending Data",
                    ),
                ),
                (
                    "has_2yrs_net_assets",
                    models.BooleanField(
                        db_column="has_2yrs_Net_Assets",
                        verbose_name="Has 2 Yrs Net Assets Data",
                    ),
                ),
                (
                    "has_2yrs_employees",
                    models.BooleanField(
                        db_column="has_2yrs_Employees",
                        verbose_name="Has 2 Yrs Employee Data",
                    ),
                ),
                (
                    "include_in_analysis",
                    models.BooleanField(
                        db_column="include_in_analysis",
                        verbose_name="Include In Analysis",
                    ),
                ),
                (
                    "makes_grants_to_individuals",
                    models.BooleanField(
                        null=True, verbose_name="Makes Grants to Individuals"
                    ),
                ),
            ],
            options={
                "db_table": "ukgrantmaking_funders_analysis_view",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FundersTagsView",
            fields=[
                (
                    "org_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "funders_360_giving_publisher",
                    models.BooleanField(null=True, verbose_name="360 Giving Publisher"),
                ),
                (
                    "living_wage_funder",
                    models.BooleanField(null=True, verbose_name="Living Wage Funder"),
                ),
                ("aco", models.BooleanField(null=True, verbose_name="ACO")),
                (
                    "acf_current",
                    models.BooleanField(null=True, verbose_name="ACF Current"),
                ),
                (
                    "london_funders",
                    models.BooleanField(null=True, verbose_name="London Funders"),
                ),
                (
                    "yorkshire_funders",
                    models.BooleanField(null=True, verbose_name="Yorkshire Funders"),
                ),
                (
                    "west_midlands_funders_network",
                    models.BooleanField(
                        null=True, verbose_name="West Midlands Funders Network"
                    ),
                ),
                ("vonne", models.BooleanField(null=True, verbose_name="VONNE")),
                (
                    "open_trusting",
                    models.BooleanField(null=True, verbose_name="Open & Trusting"),
                ),
                (
                    "postcode_lottery",
                    models.BooleanField(null=True, verbose_name="Postcode Lottery"),
                ),
                (
                    "sainsburys_family_charitable_trusts",
                    models.BooleanField(
                        null=True, verbose_name="Sainsburys Family Charitable Trusts"
                    ),
                ),
                (
                    "funders_forum_for_ni",
                    models.BooleanField(null=True, verbose_name="Funders Forum for NI"),
                ),
                ("ukcf", models.BooleanField(null=True, verbose_name="UKCF")),
                (
                    "community_foundation",
                    models.BooleanField(null=True, verbose_name="Community Foundation"),
                ),
                (
                    "livery_company",
                    models.BooleanField(null=True, verbose_name="Livery Company"),
                ),
                ("ccew", models.BooleanField(null=True, verbose_name="CCEW")),
                ("oscr", models.BooleanField(null=True, verbose_name="OSCR")),
                ("ccni", models.BooleanField(null=True, verbose_name="CCNI")),
            ],
            options={
                "db_table": "ukgrantmaking_funders_tags_view",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GrantsAnalysisView",
            fields=[
                (
                    "grant_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=512, verbose_name="Grant Title")),
                (
                    "description",
                    models.TextField(null=True, verbose_name="Grant Description"),
                ),
                ("currency", models.CharField(max_length=10, verbose_name="Currency")),
                (
                    "amount_awarded",
                    models.DecimalField(
                        decimal_places=2, max_digits=18, verbose_name="Amount Awarded"
                    ),
                ),
                (
                    "amount_awarded_gbp",
                    models.DecimalField(
                        db_column="amount_awarded_GBP",
                        decimal_places=2,
                        max_digits=18,
                        verbose_name="Amount Awarded (GBP)",
                    ),
                ),
                ("award_date", models.DateField(null=True, verbose_name="Award Date")),
                (
                    "regrant_type",
                    models.CharField(
                        max_length=50, null=True, verbose_name="Regrant Type"
                    ),
                ),
                (
                    "planned_dates_duration",
                    models.IntegerField(
                        null=True, verbose_name="Planned Duration (Months)"
                    ),
                ),
                (
                    "planned_dates_start_date",
                    models.DateField(
                        db_column="planned_dates_startDate",
                        null=True,
                        verbose_name="Planned Start Date",
                    ),
                ),
                (
                    "planned_dates_end_date",
                    models.DateField(
                        db_column="planned_dates_endDate",
                        null=True,
                        verbose_name="Planned End Date",
                    ),
                ),
                (
                    "inclusion",
                    models.CharField(
                        max_length=50, null=True, verbose_name="Inclusion Status"
                    ),
                ),
                (
                    "duration_band",
                    models.CharField(max_length=50, verbose_name="Duration Band"),
                ),
                (
                    "grant_amount_band",
                    models.CharField(max_length=50, verbose_name="Grant Amount Band"),
                ),
                (
                    "recipient_id",
                    models.CharField(max_length=50, verbose_name="Recipient ID"),
                ),
                (
                    "recipient_organisation_id",
                    models.CharField(
                        max_length=50, null=True, verbose_name="Recipient Org ID"
                    ),
                ),
                (
                    "recipient_organisation_name",
                    models.CharField(max_length=255, verbose_name="Recipient Org Name"),
                ),
                (
                    "recipient_type",
                    models.CharField(
                        max_length=50, null=True, verbose_name="Recipient Type"
                    ),
                ),
                (
                    "regulator_name",
                    models.CharField(
                        db_column="regulator_name",
                        max_length=255,
                        verbose_name="Regulator Name",
                    ),
                ),
                (
                    "regulator_type",
                    models.CharField(
                        db_column="regulator_type",
                        max_length=50,
                        verbose_name="Regulator Type",
                    ),
                ),
                (
                    "regulator_date_of_registration",
                    models.DateField(
                        db_column="regulator_date_of_registration",
                        null=True,
                        verbose_name="Regulator Registration Date",
                    ),
                ),
                (
                    "regulator_scale",
                    models.CharField(
                        db_column="regulator_scale",
                        max_length=50,
                        null=True,
                        verbose_name="Regulator Scale",
                    ),
                ),
                (
                    "regulator_how",
                    models.CharField(
                        db_column="regulator_how",
                        max_length=255,
                        null=True,
                        verbose_name="Regulator How",
                    ),
                ),
                (
                    "regulator_who",
                    models.CharField(
                        db_column="regulator_who",
                        max_length=255,
                        null=True,
                        verbose_name="Regulator Who",
                    ),
                ),
                (
                    "regulator_what",
                    models.CharField(
                        db_column="regulator_what",
                        max_length=255,
                        null=True,
                        verbose_name="Regulator What",
                    ),
                ),
                (
                    "regulator_london_aoo",
                    models.BooleanField(
                        db_column="regulator_london_aoo",
                        null=True,
                        verbose_name="Regulator AOO is London",
                    ),
                ),
                (
                    "regulator_london_hq",
                    models.BooleanField(
                        db_column="regulator_london_hq",
                        null=True,
                        verbose_name="Regulator HQ is London",
                    ),
                ),
                (
                    "regulator_ctry_hq_name",
                    models.CharField(
                        db_column="regulator_ctry_hq_name",
                        max_length=255,
                        null=True,
                        verbose_name="Regulator HQ Country Name",
                    ),
                ),
                (
                    "regulator_rgn_hq_name",
                    models.CharField(
                        db_column="regulator_rgn_hq_name",
                        max_length=255,
                        null=True,
                        verbose_name="Regulator HQ Region Name",
                    ),
                ),
                (
                    "regulator_la_hq_name",
                    models.CharField(
                        db_column="regulator_la_hq_name",
                        max_length=255,
                        null=True,
                        verbose_name="Regulator HQ LA Name",
                    ),
                ),
                (
                    "regulator_ctry_aoo_name",
                    models.CharField(
                        db_column="regulator_ctry_aoo_name",
                        max_length=255,
                        null=True,
                        verbose_name="Regulator AOO Country Name",
                    ),
                ),
                (
                    "regulator_rgn_aoo_name",
                    models.CharField(
                        db_column="regulator_rgn_aoo_name",
                        max_length=255,
                        null=True,
                        verbose_name="Regulator AOO Region Name",
                    ),
                ),
                (
                    "regulator_la_aoo_name",
                    models.CharField(
                        db_column="regulator_la_aoo_name",
                        max_length=255,
                        null=True,
                        verbose_name="Regulator AOO LA Name",
                    ),
                ),
                (
                    "financial_year_end",
                    models.DateField(
                        null=True, verbose_name="Recipient Financial Year End"
                    ),
                ),
                (
                    "income",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Recipient Income",
                    ),
                ),
                (
                    "spending",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Recipient Spending",
                    ),
                ),
                (
                    "employees",
                    models.IntegerField(null=True, verbose_name="Recipient Employees"),
                ),
                (
                    "income_band",
                    models.CharField(
                        max_length=50, null=True, verbose_name="Income Band (Org Size)"
                    ),
                ),
                (
                    "funding_organisation_id",
                    models.CharField(max_length=50, verbose_name="Funding Org ID"),
                ),
                (
                    "funding_organisation_name",
                    models.CharField(max_length=255, verbose_name="Funding Org Name"),
                ),
                (
                    "funding_organisation_department",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Funding Org Department"
                    ),
                ),
                (
                    "funder_id",
                    models.CharField(max_length=50, verbose_name="Funder ID"),
                ),
                (
                    "funding_organisation_type",
                    models.CharField(max_length=50, verbose_name="Funding Org Type"),
                ),
                (
                    "funder_segment",
                    models.CharField(
                        db_column="segment",
                        max_length=50,
                        verbose_name="Funder Segment",
                    ),
                ),
                (
                    "funder_category",
                    models.CharField(
                        db_column="category",
                        max_length=50,
                        verbose_name="Funder Category",
                    ),
                ),
                (
                    "funder_name",
                    models.CharField(
                        db_column="funder_name",
                        max_length=255,
                        verbose_name="Funder Name",
                    ),
                ),
                (
                    "funder_la_hq_name",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Funder HQ LA Name"
                    ),
                ),
                (
                    "funder_rgn_hq_name",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Funder HQ Region Name"
                    ),
                ),
                (
                    "funder_ctry_hq_name",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Funder HQ Country Name"
                    ),
                ),
                (
                    "funder_la_aoo_name",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Funder AOO LA Name"
                    ),
                ),
                (
                    "funder_rgn_aoo_name",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Funder AOO Region Name"
                    ),
                ),
                (
                    "funder_ctry_aoo_name",
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name="Funder AOO Country Name",
                    ),
                ),
            ],
            options={
                "db_table": "ukgrantmaking_grants_analysis_view",
                "managed": False,
            },
        ),
    ]
