# Generated by Django 5.2.8 on 2025-12-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ukgrantmaking", "0130_alter_cleaningstatus_sort_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="funder",
            name="overseas_aoo",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="funder",
            name="overseas_aoo_name",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="grantrecipient",
            name="overseas_aoo",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="grantrecipient",
            name="overseas_aoo_name",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
