# Generated by Django 5.2.8 on 2026-02-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ukgrantmaking', '0134_auto_20260128_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundersRegionalView',
            fields=[
                ('org_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('segment', models.CharField(max_length=50, verbose_name='Segment')),
                ('category', models.CharField(max_length=50, verbose_name='Category')),
                ('scale', models.CharField(max_length=255, null=True, verbose_name='Funder Scale')),
                ('grantmaking', models.DecimalField(decimal_places=3, max_digits=18, null=True, verbose_name='Grantmaking GBP m')),
                ('geoarea', models.CharField(max_length=255, null=True, verbose_name='Geographical Area')),
                ('overseas', models.BooleanField(null=True, verbose_name='Overseas')),
                ('england', models.BooleanField(null=True, verbose_name='England')),
                ('northern_ireland', models.BooleanField(null=True, verbose_name='Northern Ireland')),
                ('scotland', models.BooleanField(null=True, verbose_name='Scotland')),
                ('wales', models.BooleanField(null=True, verbose_name='Wales')),
                ('england_northeast', models.BooleanField(null=True, verbose_name='England - North East')),
                ('england_northwest', models.BooleanField(null=True, verbose_name='England - North West')),
                ('england_yorkshire', models.BooleanField(null=True, verbose_name='England - Yorkshire and the Humber')),
                ('england_eastmidlands', models.BooleanField(null=True, verbose_name='England - East Midlands')),
                ('england_westmidlands', models.BooleanField(null=True, verbose_name='England - West Midlands')),
                ('england_east', models.BooleanField(null=True, verbose_name='England - East of England')),
                ('england_london', models.BooleanField(null=True, verbose_name='England - London')),
                ('england_southeast', models.BooleanField(null=True, verbose_name='England - South East')),
                ('england_southwest', models.BooleanField(null=True, verbose_name='England - South West')),
            ],
            options={
                'db_table': 'ukgrantmaking_funders_regional_view',
                'managed': False,
            },
        ),
    ]
