# Generated by Django 5.2.8 on 2026-02-05 10:40

import django_db_views.migration_functions
import django_db_views.operations
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ukgrantmaking", "0135_fundersregionalview"),
    ]

    operations = [
        django_db_views.operations.ViewRunPython(
            code=django_db_views.migration_functions.ForwardViewMigration(
                'WITH base AS (\n            SELECT org_id,\n                "name",\n                segment,\n                category,\n                "scale",\n                f."year1_Grantmaking_GBP_m" AS "grantmaking",\n                "scale" ILIKE \'%%overseas%%\' AS "overseas",\n                ctry_aoo::jsonb ? \'E92000001\' AS "england",\n                ctry_aoo::jsonb ? \'N92000002\' AS "northern_ireland",\n                ctry_aoo::jsonb ? \'S92000003\' AS "scotland",\n                ctry_aoo::jsonb ? \'W92000004\' AS "wales",\n                rgn_aoo::jsonb ? \'E12000001\' AS "england_northeast",\n                rgn_aoo::jsonb ? \'E12000002\' AS "england_northwest",\n                rgn_aoo::jsonb ? \'E12000003\' AS "england_yorkshire",\n                rgn_aoo::jsonb ? \'E12000004\' AS "england_eastmidlands",\n                rgn_aoo::jsonb ? \'E12000005\' AS "england_westmidlands",\n                rgn_aoo::jsonb ? \'E12000006\' AS "england_east",\n                rgn_aoo::jsonb ? \'E12000007\' AS "england_london",\n                rgn_aoo::jsonb ? \'E12000008\' AS "england_southeast",\n                rgn_aoo::jsonb ? \'E12000009\' AS "england_southwest"\n            FROM ukgrantmaking_funders_analysis_view f\n            ORDER BY f."year1_Grantmaking_Rank"\n        )\n        SELECT org_id,\n            "name",\n            segment,\n            category,\n            "scale",\n            grantmaking,\n            CASE WHEN "scale" IN (\'National and Overseas\', \'Overseas\') THEN "scale"\n                WHEN "scale" = \'National\' THEN \n                    CASE WHEN "england" AND "northern_ireland" AND "scotland" AND "wales" THEN \'United Kingdom\'\n                        WHEN "england" AND "scotland" AND "wales" THEN \'Great Britain\'\n                        WHEN "england" AND "wales" THEN \'England and Wales\'\n                        WHEN "england" THEN \'England\'\n                        WHEN "wales" THEN \'Wales\'\n                        WHEN "scotland" THEN \'Scotland\'\n                        WHEN "northern_ireland" THEN \'Northern Ireland\'\n                        ELSE \'Other National\' END\n                WHEN "scale" = \'Regional\' THEN \'Regional\'\n                WHEN "scale" = \'Local\' THEN \'Local\'\n                ELSE \'Other\' END AS "geoarea",\n            "overseas",\n            "england",\n            "northern_ireland",\n            "scotland",\n            "wales",\n            "england_northeast",\n            "england_northwest",\n            "england_yorkshire",\n            "england_eastmidlands",\n            "england_westmidlands",\n            "england_east",\n            "england_london",\n            "england_southeast",\n            "england_southwest"\n        FROM base\n        ORDER BY grantmaking DESC NULLS LAST',
                "ukgrantmaking_funders_regional_view",
                engine="django.db.backends.postgresql",
            ),
            reverse_code=django_db_views.migration_functions.BackwardViewMigration(
                "",
                "ukgrantmaking_funders_regional_view",
                engine="django.db.backends.postgresql",
            ),
            atomic=False,
        ),
    ]
