# Generated by Django 5.2.8 on 2026-03-30 10:28

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ukgrantmaking", "0142_auto_20260312_1713"),
    ]

    operations = [
        migrations.RenameField(
            model_name="grant",
            old_name="award_date",
            new_name="award_date_registered",
        ),
        migrations.RenameField(
            model_name="grantrecipient",
            old_name="type",
            new_name="type_registered",
        ),
        migrations.AddField(
            model_name="grant",
            name="award_date_manual",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="grantrecipient",
            name="type_manual",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Organisation", "Organisation"),
                    ("Individual", "Individual"),
                    ("Charity", "Charity"),
                    ("Community Interest Company", "Community Interest Company"),
                    ("Education", "Education"),
                    ("Government Department", "Government Department"),
                    ("Local Authority", "Local Authority"),
                    ("Mutual", "Mutual"),
                    ("NDPB", "NDPB"),
                    ("NHS", "NHS"),
                    ("Non-profit Company", "Non-profit Company"),
                    ("Overseas Charity", "Overseas Charity"),
                    ("Overseas Government", "Overseas Government"),
                    ("Private Company", "Private Company"),
                    ("University", "University"),
                    ("Religious Organisation", "Religious Organisation"),
                    ("Sports Club", "Sports Club"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="grant",
            name="award_date",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Coalesce(
                    "award_date_manual", "award_date_registered"
                ),
                output_field=models.DateField(),
            ),
        ),
        migrations.AddField(
            model_name="grantrecipient",
            name="type",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Coalesce(
                    "type_manual", "type_registered"
                ),
                output_field=models.CharField(blank=True, max_length=50, null=True),
            ),
        ),
        migrations.AddField(
            model_name="grant",
            name="file_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
