name: Django tests
on: [push, pull_request]
jobs:
  django-test:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: "sqlite:///:memory:"
      SECRET_KEY: 1234567890

    steps:
      - uses: actions/checkout@v3
      - name: Parse Python version
        run: sed  s/python-// runtime.txt | head > .python-version
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version-file: ".python-version"
      - name: psycopg2 prerequisites
        run: sudo apt-get install libxml2-dev libxslt-dev python3-dev libpq-dev
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run migrations
        run: |
          python manage.py migrate
          python manage.py collectstatic
      - name: Test with django test
        run: |
          python manage.py test
